PARSING_SCHEME = {
    "assist_percentage": 'td[data-stat="ast_pct"]:first',
    "assists": 'td[data-stat="ast"]:first',
    "away_losses": 'td[data-stat="losses_visitor"]:first',
    "away_wins": 'td[data-stat="wins_visitor"]:first',
    "block_percentage": 'td[data-stat="blk_pct"]:first',
    "blocks": 'td[data-stat="blk"]:first',
    "conference_losses": 'td[data-stat="losses_conf"]:first',
    "conference_wins": 'td[data-stat="wins_conf"]:first',
    "defensive_rebounds": 'td[data-stat="drb"]:first',
    "effective_field_goal_percentage": 'td[data-stat="efg_pct"]:first',
    "field_goal_attempts": 'td[data-stat="fga"]:first',
    "field_goal_percentage": 'td[data-stat="fg_pct"]:first',
    "field_goals": 'td[data-stat="fg"]:first',
    "free_throw_attempt_rate": 'td[data-stat="fta_per_fga_pct"]:first',
    "free_throw_attempts": 'td[data-stat="fta"]:first',
    "free_throw_percentage": 'td[data-stat="ft_pct"]:first',
    "free_throws_per_field_goal_attempt": 'td[data-stat="ft_rate"]:first',
    "free_throws": 'td[data-stat="ft"]:first',
    "games_played": 'td[data-stat="g"]:first',
    "home_losses": 'td[data-stat="losses_home"]:first',
    "home_wins": 'td[data-stat="wins_home"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "minutes_played": 'td[data-stat="mp"]:first',
    "name": "a",
    "offensive_rating": 'td[data-stat="off_rtg"]:first',
    "offensive_rebound_percentage": 'td[data-stat="orb_pct"]:first',
    "offensive_rebounds": 'td[data-stat="orb"]:first',
    "opp_assist_percentage": 'td[data-stat="opp_ast_pct"]:first',
    "opp_assists": 'td[data-stat="opp_ast"]:first',
    "opp_block_percentage": 'td[data-stat="opp_blk_pct"]:first',
    "opp_blocks": 'td[data-stat="opp_blk"]:first',
    "opp_defensive_rebounds": 'td[data-stat="opp_drb"]:first',
    "opp_effective_field_goal_percentage": 'td[data-stat="opp_efg_pct"]:first',
    "opp_field_goal_attempts": 'td[data-stat="opp_fga"]:first',
    "opp_field_goal_percentage": 'td[data-stat="opp_fg_pct"]:first',
    "opp_field_goals": 'td[data-stat="opp_fg"]:first',
    "opp_free_throw_attempt_rate": 'td[data-stat="opp_fta_per_fga_pct"]:first',
    "opp_free_throw_attempts": 'td[data-stat="opp_fta"]:first',
    "opp_free_throw_percentage": 'td[data-stat="opp_ft_pct"]:first',
    "opp_free_throws_per_field_goal_attempt": 'td[data-stat="opp_ft_rate"]:first',
    "opp_free_throws": 'td[data-stat="opp_ft"]:first',
    "opp_minutes_played": 'td[data-stat="opp_mp"]:first',
    "opp_offensive_rating": 'td[data-stat="def_rtg"]:first',
    "opp_offensive_rebound_percentage": 'td[data-stat="opp_orb_pct"]:first',
    "opp_offensive_rebounds": 'td[data-stat="opp_orb"]:first',
    "opp_personal_fouls": 'td[data-stat="opp_pf"]:first',
    "opp_points": 'td[data-stat="opp_pts"]:first',
    "opp_steal_percentage": 'td[data-stat="opp_stl_pct"]:first',
    "opp_steals": 'td[data-stat="opp_stl"]:first',
    "opp_three_point_attempt_rate": 'td[data-stat="opp_fg3a_per_fga_pct"]:first',
    "opp_three_point_field_goal_attempts": 'td[data-stat="opp_fg3a"]:first',
    "opp_three_point_field_goal_percentage": 'td[data-stat="opp_fg3_pct"]:first',
    "opp_three_point_field_goals": 'td[data-stat="opp_fg3"]:first',
    "opp_total_rebound_percentage": 'td[data-stat="opp_trb_pct"]:first',
    "opp_total_rebounds": 'td[data-stat="opp_trb"]:first',
    "opp_true_shooting_percentage": 'td[data-stat="opp_ts_pct"]:first',
    "opp_turnover_percentage": 'td[data-stat="opp_tov_pct"]:first',
    "opp_turnovers": 'td[data-stat="opp_tov"]:first',
    "opp_two_point_field_goal_attempts": 'td[data-stat="opp_fg2a"]:first',
    "opp_two_point_field_goal_percentage": 'td[data-stat="opp_fg2_pct"]:first',
    "opp_two_point_field_goals": 'td[data-stat="opp_fg2"]:first',
    "pace": 'td[data-stat="pace"]:first',
    "personal_fouls": 'td[data-stat="pf"]:first',
    "points": 'td[data-stat="pts"]:first',
    "simple_rating_system": 'td[data-stat="srs"]:first',
    "steal_percentage": 'td[data-stat="stl_pct"]:first',
    "steals": 'td[data-stat="stl"]:first',
    "strength_of_schedule": 'td[data-stat="sos"]:first',
    "three_point_attempt_rate": 'td[data-stat="fg3a_per_fga_pct"]:first',
    "three_point_field_goal_attempts": 'td[data-stat="fg3a"]:first',
    "three_point_field_goal_percentage": 'td[data-stat="fg3_pct"]:first',
    "three_point_field_goals": 'td[data-stat="fg3"]:first',
    "total_rebound_percentage": 'td[data-stat="trb_pct"]:first',
    "total_rebounds": 'td[data-stat="trb"]:first',
    "true_shooting_percentage": 'td[data-stat="ts_pct"]:first',
    "turnover_percentage": 'td[data-stat="tov_pct"]:first',
    "turnovers": 'td[data-stat="tov"]:first',
    "two_point_field_goal_attempts": 'td[data-stat="fg2a"]:first',
    "two_point_field_goal_percentage": 'td[data-stat="fg2_pct"]:first',
    "two_point_field_goals": 'td[data-stat="fg2"]:first',
    "win_percentage": 'td[data-stat="win_loss_pct"]:first',
    "wins": 'td[data-stat="wins"]:first',
}

SCHEDULE_SCHEME = {
    "arena": 'td[data-stat="arena"]:first',
    "date": 'td[data-stat="date_game"]:first',
    "game": 'th[data-stat="g"]:first',
    "location": 'td[data-stat="game_location"]:first',
    "opponent_abbr": 'td[data-stat="opp_name"]:first',
    "opponent_conference": 'td[data-stat="conf_abbr"]:first',
    "opponent_name": 'td[data-stat="opp_name"]:first',
    "overtimes": 'td[data-stat="overtimes"]:first',
    "points_against": 'td[data-stat="opp_pts"]:first',
    "points_for": 'td[data-stat="pts"]:first',
    "result": 'td[data-stat="game_result"]:first',
    "season_losses": 'td[data-stat="losses"]:first',
    "season_wins": 'td[data-stat="wins"]:first',
    "streak": 'td[data-stat="game_streak"]:first',
    "time": 'td[data-stat="time_game"]:first',
    "type": 'td[data-stat="game_type"]:first',
}

BOXSCORE_SCHEME = {
    "away_assist_percentage": 'tfoot td[data-stat="ast_pct"]',
    "away_assists": 'tfoot td[data-stat="ast"]',
    "away_block_percentage": 'tfoot td[data-stat="blk_pct"]',
    "away_blocks": 'tfoot td[data-stat="blk"]',
    "away_defensive_rating": 'tfoot td[data-stat="def_rtg"]',
    "away_defensive_rebound_percentage": 'tfoot td[data-stat="drb_pct"]',
    "away_defensive_rebounds": 'tfoot td[data-stat="drb"]',
    "away_effective_field_goal_percentage": 'tfoot td[data-stat="efg_pct"]',
    "away_field_goal_attempts": 'tfoot td[data-stat="fga"]',
    "away_field_goal_percentage": 'tfoot td[data-stat="fg_pct"]',
    "away_field_goals": 'tfoot td[data-stat="fg"]',
    "away_free_throw_attempt_rate": 'tfoot td[data-stat="fta_per_fga_pct"]',
    "away_free_throw_attempts": 'tfoot td[data-stat="fta"]',
    "away_free_throw_percentage": 'tfoot td[data-stat="ft_pct"]',
    "away_free_throws": 'tfoot td[data-stat="ft"]',
    "away_minutes_played": 'tfoot td[data-stat="mp"]',
    "away_name": 'a[itemprop="name"]:first',
    "away_offensive_rating": 'tfoot td[data-stat="off_rtg"]',
    "away_offensive_rebound_percentage": 'tfoot td[data-stat="orb_pct"]',
    "away_offensive_rebounds": 'tfoot td[data-stat="orb"]',
    "away_personal_fouls": 'tfoot td[data-stat="pf"]',
    "away_points": 'tfoot td[data-stat="pts"]',
    "away_ranking": 'div[class="game_summary nohover current"] tr',
    "away_record": 'div#boxes div[class="section_heading"] h2',
    "away_steal_percentage": 'tfoot td[data-stat="stl_pct"]',
    "away_steals": 'tfoot td[data-stat="stl"]',
    "away_three_point_attempt_rate": 'tfoot td[data-stat="fg3a_per_fga_pct"]',
    "away_three_point_field_goal_attempts": 'tfoot td[data-stat="fg3a"]',
    "away_three_point_field_goal_percentage": 'tfoot td[data-stat="fg3_pct"]',
    "away_three_point_field_goals": 'tfoot td[data-stat="fg3"]',
    "away_total_rebound_percentage": 'tfoot td[data-stat="trb_pct"]',
    "away_total_rebounds": 'tfoot td[data-stat="trb"]',
    "away_true_shooting_percentage": 'tfoot td[data-stat="ts_pct"]',
    "away_turnover_percentage": 'tfoot td[data-stat="tov_pct"]',
    "away_turnovers": 'tfoot td[data-stat="tov"]',
    "away_two_point_field_goal_attempts": 'tfoot td[data-stat="fg2a"]',
    "away_two_point_field_goal_percentage": 'tfoot td[data-stat="fg2_pct"]',
    "away_two_point_field_goals": 'tfoot td[data-stat="fg2"]',
    "date": 'div[class="scorebox_meta"]',
    "home_assist_percentage": 'tfoot td[data-stat="ast_pct"]',
    "home_assists": 'tfoot td[data-stat="ast"]',
    "home_block_percentage": 'tfoot td[data-stat="blk_pct"]',
    "home_blocks": 'tfoot td[data-stat="blk"]',
    "home_defensive_rating": 'tfoot td[data-stat="def_rtg"]',
    "home_defensive_rebound_percentage": 'tfoot td[data-stat="drb_pct"]',
    "home_defensive_rebounds": 'tfoot td[data-stat="drb"]',
    "home_effective_field_goal_percentage": 'tfoot td[data-stat="efg_pct"]',
    "home_field_goal_attempts": 'tfoot td[data-stat="fga"]',
    "home_field_goal_percentage": 'tfoot td[data-stat="fg_pct"]',
    "home_field_goals": 'tfoot td[data-stat="fg"]',
    "home_free_throw_attempt_rate": 'tfoot td[data-stat="fta_per_fga_pct"]',
    "home_free_throw_attempts": 'tfoot td[data-stat="fta"]',
    "home_free_throw_percentage": 'tfoot td[data-stat="ft_pct"]',
    "home_free_throws": 'tfoot td[data-stat="ft"]',
    "home_minutes_played": 'tfoot td[data-stat="mp"]',
    "home_name": 'a[itemprop="name"]:last',
    "home_offensive_rating": 'tfoot td[data-stat="off_rtg"]',
    "home_offensive_rebound_percentage": 'tfoot td[data-stat="orb_pct"]',
    "home_offensive_rebounds": 'tfoot td[data-stat="orb"]',
    "home_personal_fouls": 'tfoot td[data-stat="pf"]',
    "home_points": 'tfoot td[data-stat="pts"]',
    "home_ranking": 'div[class="game_summary nohover current"] tr',
    "home_record": 'div#boxes div[class="section_heading"] h2',
    "home_steal_percentage": 'tfoot td[data-stat="stl_pct"]',
    "home_steals": 'tfoot td[data-stat="stl"]',
    "home_three_point_attempt_rate": 'tfoot td[data-stat="fg3a_per_fga_pct"]',
    "home_three_point_field_goal_attempts": 'tfoot td[data-stat="fg3a"]',
    "home_three_point_field_goal_percentage": 'tfoot td[data-stat="fg3_pct"]',
    "home_three_point_field_goals": 'tfoot td[data-stat="fg3"]',
    "home_total_rebound_percentage": 'tfoot td[data-stat="trb_pct"]',
    "home_total_rebounds": 'tfoot td[data-stat="trb"]',
    "home_true_shooting_percentage": 'tfoot td[data-stat="ts_pct"]',
    "home_turnover_percentage": 'tfoot td[data-stat="tov_pct"]',
    "home_turnovers": 'tfoot td[data-stat="tov"]',
    "home_two_point_field_goal_attempts": 'tfoot td[data-stat="fg2a"]',
    "home_two_point_field_goal_percentage": 'tfoot td[data-stat="fg2_pct"]',
    "home_two_point_field_goals": 'tfoot td[data-stat="fg2"]',
    "location": 'div[class="scorebox_meta"]',
    "losing_abbr": "",
    "losing_name": "",
    "pace": 'td[data-stat="pace"]:first',
    "summary": "table#line-score",
    "winning_abbr": "",
    "winning_name": "",
}

BOXSCORE_ELEMENT_INDEX = {
    "away_ranking": 0,
    "date": 0,
    "home_assist_percentage": 1,
    "home_assists": 1,
    "home_block_percentage": 1,
    "home_blocks": 1,
    "home_defensive_rating": 1,
    "home_defensive_rebound_percentage": 1,
    "home_defensive_rebounds": 1,
    "home_effective_field_goal_percentage": 1,
    "home_field_goal_attempts": 1,
    "home_field_goal_percentage": 1,
    "home_field_goals": 1,
    "home_free_throw_attempt_rate": 1,
    "home_free_throw_attempts": 1,
    "home_free_throw_percentage": 1,
    "home_free_throws": 1,
    "home_minutes_played": 1,
    "home_offensive_rating": 1,
    "home_offensive_rebound_percentage": 1,
    "home_offensive_rebounds": 1,
    "home_personal_fouls": 1,
    "home_points": 1,
    "home_ranking": 1,
    "home_record": 1,
    "home_steal_percentage": 1,
    "home_steals": 1,
    "home_three_point_attempt_rate": 1,
    "home_three_point_field_goal_attempts": 1,
    "home_three_point_field_goal_percentage": 1,
    "home_three_point_field_goals": 1,
    "home_total_rebound_percentage": 1,
    "home_total_rebounds": 1,
    "home_true_shooting_percentage": 1,
    "home_turnover_percentage": 1,
    "home_turnovers": 1,
    "home_two_point_field_goal_attempts": 1,
    "home_two_point_field_goal_percentage": 1,
    "home_two_point_field_goals": 1,
    "location": 1,
}

RANKINGS_SCHEME = {
    "change": 'td[data-stat="rank_diff"]',
    "date": 'td[data-stat="date_poll"]',
    "name": 'td[data-stat="school_name"]',
    "previous": 'td[data-stat="rank_prev"]',
    "rank": 'td[data-stat="rank"]',
    "week": 'th[data-stat="week_poll"]',
}

PLAYER_SCHEME = {
    "age": "nobr",
    "assist_percentage": 'td[data-stat="ast_pct"]',
    "assists": 'td[data-stat="ast"]',
    "birth_date": 'td[data-stat=""]',
    "block_percentage": 'td[data-stat="blk_pct"]',
    "blocks": 'td[data-stat="blk"]',
    "box_plus_minus": 'td[data-stat="bpm"]',
    "conference": 'td[data-stat="conf_abbr"]',
    "defensive_box_plus_minus": 'td[data-stat="dbpm"]',
    "defensive_rating": 'td[data-stat="def_rtg"]',
    "defensive_rebound_percentage": 'td[data-stat="drb_pct"]',
    "defensive_rebounds": 'td[data-stat="drb"]',
    "defensive_win_shares": 'td[data-stat="dws"]',
    "effective_field_goal_percentage": 'td[data-stat="efg_pct"]',
    "field_goal_attempts": 'td[data-stat="fga"]',
    "field_goal_percentage": 'td[data-stat="fg_pct"]',
    "field_goals": 'td[data-stat="fg"]',
    "free_throw_attempt_rate": 'td[data-stat="fta_per_fga_pct"]',
    "free_throw_attempts": 'td[data-stat="fta"]',
    "free_throw_percentage": 'td[data-stat="ft_pct"]',
    "free_throws": 'td[data-stat="ft"]',
    "games_played": 'td[data-stat="g"]',
    "games_started": 'td[data-stat="gs"]',
    "height": 'span[itemprop="height"]',
    "minutes_played": 'td[data-stat="mp"]',
    "name": "h1",
    "nationality": 'td[data-stat=""]',
    "offensive_box_plus_minus": 'td[data-stat="obpm"]',
    "offensive_rating": 'td[data-stat="off_rtg"]',
    "offensive_rebound_percentage": 'td[data-stat="orb_pct"]',
    "offensive_rebounds": 'td[data-stat="orb"]',
    "offensive_win_shares": 'td[data-stat="ows"]',
    "personal_fouls": 'td[data-stat="pf"]',
    "player_efficiency_rating": 'td[data-stat="per"]',
    "points_produced": 'td[data-stat="pprod"]',
    "points": 'td[data-stat="pts"]',
    "position": 'td[data-stat="pos"]',
    "season": 'th[data-stat="season"]:first',
    "steal_percentage": 'td[data-stat="stl_pct"]',
    "steals": 'td[data-stat="stl"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "team_abbreviation": 'td[data-stat="school_name"]',
    "three_point_attempt_rate": 'td[data-stat="fg3a_per_fga_pct"]',
    "three_point_attempts": 'td[data-stat="fg3a"]',
    "three_point_percentage": 'td[data-stat="fg3_pct"]',
    "three_pointers": 'td[data-stat="fg3"]',
    "total_rebound_percentage": 'td[data-stat="trb_pct"]',
    "total_rebounds": 'td[data-stat="trb"]',
    "true_shooting_percentage": 'td[data-stat="ts_pct"]',
    "turnover_percentage": 'td[data-stat="tov_pct"]',
    "turnovers": 'td[data-stat="tov"]',
    "two_point_attempts": 'td[data-stat="fg2a"]',
    "two_point_percentage": 'td[data-stat="fg2_pct"]',
    "two_pointers": 'td[data-stat="fg2"]',
    "usage_percentage": 'td[data-stat="usg_pct"]',
    "weight": 'span[itemprop="weight"]',
    "win_shares_per_40_minutes": 'td[data-stat="ws_per_40"]',
    "win_shares": 'td[data-stat="ws"]',
}

BASIC_STATS_URL = "https://www.sports-reference.com/cbb/seasons/%s-school-stats.html"
BASIC_OPPONENT_STATS_URL = "https://www.sports-reference.com/cbb/seasons/%s-opponent-stats.html"
ADVANCED_STATS_URL = "https://www.sports-reference.com/cbb/seasons/%s-advanced-school-stats.html"
ADVANCED_OPPONENT_STATS_URL = (
    "https://www.sports-reference.com/cbb/seasons/%s-advanced-opponent-stats.html"
)

SCHEDULE_URL = "https://www.sports-reference.com/cbb/schools/%s/%s-schedule.html"
BOXSCORE_URL = "https://www.sports-reference.com/cbb/boxscores/%s.html"
BOXSCORES_URL = "https://www.sports-reference.com/cbb/boxscores/index.cgi?month=%s&day=%s&year=%s"
RANKINGS_URL = "https://www.sports-reference.com/cbb/seasons/%s-polls-old.html"
CONFERENCES_URL = "https://www.sports-reference.com/cbb/seasons/%s.html"
CONFERENCE_URL = "https://www.sports-reference.com/cbb/conferences/%s/%s.html"
PLAYER_URL = "https://www.sports-reference.com/cbb/players/%s.html"
ROSTER_URL = "https://www.sports-reference.com/cbb/schools/%s/%s.html"

NCAA_TOURNAMENT = "NCAA"
NIT_TOURNAMENT = "NIT"
CBI_TOURNAMENT = "CBI"
CIT_TOURNAMENT = "CIT"
