PARSING_SCHEME = {
    "defensive_simple_rating_system": 'td[data-stat="srs_defense"]:first',
    "first_downs_from_penalties": 'td[data-stat="pen_fd"]:first',
    "first_downs": 'td[data-stat="first_down"]:first',
    "fumbles": 'td[data-stat="fumbles_lost"]:first',
    "games_played": 'td[data-stat="g"]:first',
    "interceptions": 'td[data-stat="pass_int"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "margin_of_victory": 'td[data-stat="mov"]:first',
    "name": "a",
    "offensive_simple_rating_system": 'td[data-stat="srs_offense"]:first',
    "pass_attempts": 'td[data-stat="pass_att"]:first',
    "pass_completions": 'td[data-stat="pass_cmp"]:first',
    "pass_first_downs": 'td[data-stat="pass_fd"]:first',
    "pass_net_yards_per_attempt": 'td[data-stat="pass_net_yds_per_att"]:first',
    "pass_touchdowns": 'td[data-stat="pass_td"]:first',
    "pass_yards": 'td[data-stat="pass_yds"]:first',
    "penalties": 'td[data-stat="penalties"]:first',
    "percent_drives_with_points": 'td[data-stat="score_pct"]:first',
    "percent_drives_with_turnovers": 'td[data-stat="turnover_pct"]:first',
    "plays": 'td[data-stat="plays_offense"]:first',
    "points_against": 'td[data-stat="points_opp"]:first',
    "points_contributed_by_offense": 'td[data-stat="exp_pts_tot"]:first',
    "points_difference": 'td[data-stat="points_diff"]:first',
    "points_for": 'td[data-stat="points"]:first',
    "rush_attempts": 'td[data-stat="rush_att"]:first',
    "rush_first_downs": 'td[data-stat="rush_fd"]:first',
    "rush_touchdowns": 'td[data-stat="rush_td"]:first',
    "rush_yards_per_attempt": 'td[data-stat="rush_yds_per_att"]:first',
    "rush_yards": 'td[data-stat="rush_yds"]:first',
    "simple_rating_system": 'td[data-stat="srs_total"]:first',
    "strength_of_schedule": 'td[data-stat="sos_total"]:first',
    "turnovers": 'td[data-stat="turnovers"]:first',
    "win_percentage": 'td[data-stat="win_loss_perc"]:first',
    "wins": 'td[data-stat="wins"]:first',
    "yards_from_penalties": 'td[data-stat="penalties_yds"]:first',
    "yards_per_play": 'td[data-stat="yds_per_play_offense"]:first',
    "yards": 'td[data-stat="total_yards"]:first',
}

SCHEDULE_SCHEME = {
    "date": 'td[data-stat="game_date"]:first',
    "day": 'td[data-stat="game_day_of_week"]:first',
    "extra_points_attempted": 'td[data-stat="xpa"]:first',
    "extra_points_made": 'td[data-stat="xpm"]:first',
    "field_goals_attempted": 'td[data-stat="fga"]:first',
    "field_goals_made": 'td[data-stat="fgm"]:first',
    "fourth_down_attempts": 'td[data-stat="fourth_down_att"]:first',
    "fourth_down_conversions": 'td[data-stat="fourth_down_success"]:first',
    "interceptions": 'td[data-stat="pass_int"]:first',
    "location": 'td[data-stat="game_location"]:first',
    "opponent_name": 'td[data-stat="opp"]:first',
    "overtime": 'td[data-stat="overtime"]:first',
    "pass_attempts": 'td[data-stat="pass_att"]:first',
    "pass_completion_rate": 'td[data-stat="pass_cmp_perc"]:first',
    "pass_completions": 'td[data-stat="pass_cmp"]:first',
    "pass_touchdowns": 'td[data-stat="pass_td"]:first',
    "pass_yards_per_attempt": 'td[data-stat="pass_yds_per_att"]:first',
    "pass_yards": 'td[data-stat="pass_yds"]:first',
    "points_allowed": 'td[data-stat="pts_def"]:first',
    "points_scored": 'td[data-stat="pts_off"]:first',
    "punt_yards": 'td[data-stat="punt_yds"]:first',
    "punts": 'td[data-stat="punt"]:first',
    "quarterback_rating": 'td[data-stat="pass_rating"]:first',
    "result": 'td[data-stat="game_outcome"]:first',
    "rush_attempts": 'td[data-stat="rush_att"]:first',
    "rush_touchdowns": 'td[data-stat="rush_td"]:first',
    "rush_yards_per_attempt": 'td[data-stat="rush_yds_per_att"]:first',
    "rush_yards": 'td[data-stat="rush_yds"]:first',
    "third_down_attempts": 'td[data-stat="third_down_att"]:first',
    "third_down_conversions": 'td[data-stat="third_down_success"]:first',
    "time_of_possession": 'td[data-stat="time_of_poss"]:first',
    "times_sacked": 'td[data-stat="pass_sacked"]:first',
    "week": 'th[data-stat="week_num"]:first',
    "yards_lost_from_sacks": 'td[data-stat="pass_sacked_yds"]:first',
}

BOXSCORE_SCHEME = {
    "away_first_downs": 'td[data-stat="vis_stat"]',
    "away_fourth_down_attempts": 'td[data-stat="vis_stat"]',
    "away_fourth_down_conversions": 'td[data-stat="vis_stat"]',
    "away_fumbles_lost": 'td[data-stat="vis_stat"]',
    "away_fumbles": 'td[data-stat="vis_stat"]',
    "away_interceptions": 'td[data-stat="vis_stat"]',
    "away_name": 'div[class="linescore_wrap"] table tbody tr:first td:nth-child(2)',
    "away_net_pass_yards": 'td[data-stat="vis_stat"]',
    "away_pass_attempts": 'td[data-stat="vis_stat"]',
    "away_pass_completions": 'td[data-stat="vis_stat"]',
    "away_pass_touchdowns": 'td[data-stat="vis_stat"]',
    "away_pass_yards": 'td[data-stat="vis_stat"]',
    "away_penalties": 'td[data-stat="vis_stat"]',
    "away_points": 'div[class="scorebox"] div[class="score"]',
    "away_rush_attempts": 'td[data-stat="vis_stat"]',
    "away_rush_touchdowns": 'td[data-stat="vis_stat"]',
    "away_rush_yards": 'td[data-stat="vis_stat"]',
    "away_third_down_attempts": 'td[data-stat="vis_stat"]',
    "away_third_down_conversions": 'td[data-stat="vis_stat"]',
    "away_time_of_possession": 'td[data-stat="vis_stat"]',
    "away_times_sacked": 'td[data-stat="vis_stat"]',
    "away_total_yards": 'td[data-stat="vis_stat"]',
    "away_turnovers": 'td[data-stat="vis_stat"]',
    "away_yards_from_penalties": 'td[data-stat="vis_stat"]',
    "away_yards_lost_from_sacks": 'td[data-stat="vis_stat"]',
    "game_details": "table#game_info tr",
    "game_info": 'div[class="scorebox_meta"]:first',
    "home_first_downs": 'td[data-stat="home_stat"]',
    "home_fourth_down_attempts": 'td[data-stat="home_stat"]',
    "home_fourth_down_conversions": 'td[data-stat="home_stat"]',
    "home_fumbles_lost": 'td[data-stat="home_stat"]',
    "home_fumbles": 'td[data-stat="home_stat"]',
    "home_interceptions": 'td[data-stat="home_stat"]',
    "home_name": 'div[class="linescore_wrap"] table tbody tr:last td:nth-child(2)',
    "home_net_pass_yards": 'td[data-stat="home_stat"]',
    "home_pass_attempts": 'td[data-stat="home_stat"]',
    "home_pass_completions": 'td[data-stat="home_stat"]',
    "home_pass_touchdowns": 'td[data-stat="home_stat"]',
    "home_pass_yards": 'td[data-stat="home_stat"]',
    "home_penalties": 'td[data-stat="home_stat"]',
    "home_points": 'div[class="scorebox"] div[class="score"]',
    "home_rush_attempts": 'td[data-stat="home_stat"]',
    "home_rush_touchdowns": 'td[data-stat="home_stat"]',
    "home_rush_yards": 'td[data-stat="home_stat"]',
    "home_third_down_attempts": 'td[data-stat="home_stat"]',
    "home_third_down_conversions": 'td[data-stat="home_stat"]',
    "home_time_of_possession": 'td[data-stat="home_stat"]',
    "home_times_sacked": 'td[data-stat="home_stat"]',
    "home_total_yards": 'td[data-stat="home_stat"]',
    "home_turnovers": 'td[data-stat="home_stat"]',
    "home_yards_from_penalties": 'td[data-stat="home_stat"]',
    "home_yards_lost_from_sacks": 'td[data-stat="home_stat"]',
    "summary": 'table[class="linescore nohover stats_table no_freeze"]:first',
    "team_stats": "table#team_stats thead",
}

BOXSCORE_ELEMENT_INDEX = {
    "attendance": 3,
    "away_first_downs": 0,
    "away_fourth_down_attempts": 10,
    "away_fourth_down_conversions": 10,
    "away_fumbles_lost": 6,
    "away_fumbles": 6,
    "away_interceptions": 2,
    "away_net_pass_yards": 4,
    "away_pass_attempts": 2,
    "away_pass_completions": 2,
    "away_pass_touchdowns": 2,
    "away_pass_yards": 2,
    "away_penalties": 8,
    "away_points": 0,
    "away_rush_attempts": 1,
    "away_rush_touchdowns": 1,
    "away_rush_yards": 1,
    "away_third_down_attempts": 9,
    "away_third_down_conversions": 9,
    "away_time_of_possession": 11,
    "away_times_sacked": 3,
    "away_total_yards": 5,
    "away_turnovers": 7,
    "away_yards_from_penalties": 8,
    "away_yards_lost_from_sacks": 3,
    "date": 0,
    "duration": 4,
    "home_first_downs": 0,
    "home_fourth_down_attempts": 10,
    "home_fourth_down_conversions": 10,
    "home_fumbles_lost": 6,
    "home_fumbles": 6,
    "home_interceptions": 2,
    "home_net_pass_yards": 4,
    "home_pass_attempts": 2,
    "home_pass_completions": 2,
    "home_pass_touchdowns": 2,
    "home_pass_yards": 2,
    "home_penalties": 8,
    "home_points": 1,
    "home_rush_attempts": 1,
    "home_rush_touchdowns": 1,
    "home_rush_yards": 1,
    "home_third_down_attempts": 9,
    "home_third_down_conversions": 9,
    "home_time_of_possession": 11,
    "home_times_sacked": 3,
    "home_total_yards": 5,
    "home_turnovers": 7,
    "home_yards_from_penalties": 8,
    "home_yards_lost_from_sacks": 3,
    "stadium": 2,
    "time": 1,
}

# Designates the index of the item within the requested tag
BOXSCORE_ELEMENT_SUB_INDEX = {
    "away_fourth_down_attempts": 1,
    "away_fourth_down_conversions": 0,
    "away_fumbles_lost": 1,
    "away_fumbles": 0,
    "away_interceptions": 4,
    "away_pass_attempts": 1,
    "away_pass_completions": 0,
    "away_pass_touchdowns": 3,
    "away_pass_yards": 2,
    "away_penalties": 0,
    "away_rush_attempts": 0,
    "away_rush_touchdowns": 2,
    "away_rush_yards": 1,
    "away_third_down_attempts": 1,
    "away_third_down_conversions": 0,
    "away_times_sacked": 0,
    "away_yards_from_penalties": 1,
    "away_yards_lost_from_sacks": 1,
    "home_fourth_down_attempts": 1,
    "home_fourth_down_conversions": 0,
    "home_fumbles_lost": 1,
    "home_fumbles": 0,
    "home_interceptions": 4,
    "home_pass_attempts": 1,
    "home_pass_completions": 0,
    "home_pass_touchdowns": 3,
    "home_pass_yards": 2,
    "home_penalties": 0,
    "home_rush_attempts": 0,
    "home_rush_touchdowns": 2,
    "home_rush_yards": 1,
    "home_third_down_attempts": 1,
    "home_third_down_conversions": 0,
    "home_times_sacked": 0,
    "home_yards_from_penalties": 1,
    "home_yards_lost_from_sacks": 1,
}

PLAYER_SCHEME = {
    "adjusted_net_yards_per_attempt_index": 'td[data-stat="pass_adj_net_yds_per_att_index"]',
    "adjusted_net_yards_per_pass_attempt": 'td[data-stat="pass_adj_net_yds_per_att"]',
    "adjusted_yards_per_attempt_index": 'td[data-stat="pass_adj_yds_per_att_index"]',
    "adjusted_yards_per_attempt": 'td[data-stat="pass_adj_yds_per_att"]',
    "all_purpose_yards": 'td[data-stat="all_purpose_yds"]',
    "approximate_value": 'td[data-stat="av"]',
    "assists_on_tackles": 'td[data-stat="tackles_assists"]',
    "attempted_passes": 'td[data-stat="pass_att"]',
    "average_kickoff_return_yards": 'td[data-stat="kick_ret_yds_per_ret"]',
    "average_punt_return_yards": 'td[data-stat="punt_ret_yds_per_ret"]',
    "birth_date": 'td[data-stat=""]',
    "blocked_punts": 'td[data-stat="punt_blocked"]',
    "catch_percentage": 'td[data-stat="catch_pct"]',
    "combined_tackles": 'td[data-stat="tackles_combined"]',
    "completed_passes": 'td[data-stat="pass_cmp"]',
    "completion_percentage_index": 'td[data-stat="pass_cmp_perc_index"]',
    "contract": 'td[data-stat=""]',
    "drop_percentage": 'td[data-stat="rec_drop_pct"]',
    "dropped_passes": 'td[data-stat="rec_drops"]',
    "espn_qbr": 'td[data-stat="qbr"]',
    "extra_point_percentage": 'td[data-stat="xp_perc"]',
    "extra_points_attempted": 'td[data-stat="xpa"]',
    "extra_points_made": 'td[data-stat="xpm"]',
    "field_goal_percentage": 'td[data-stat="fg_perc"]',
    "field_goals_attempted": 'td[data-stat="fga"]',
    "field_goals_made": 'td[data-stat="fgm"]',
    "fifty_plus_yard_field_goal_attempts": 'td[data-stat="fga5"]',
    "fifty_plus_yard_field_goals_made": 'td[data-stat="fgm5"]',
    "first_downs_receiving": 'td[data-stat="rec_first_down"]',
    "first_downs_rushing": 'td[data-stat="rush_first_down"]',
    "fourth_quarter_comebacks": 'td[data-stat="comebacks"]',
    "fourty_to_fourty_nine_yard_field_goal_attempts": 'td[data-stat="fga4"]',
    "fourty_to_fourty_nine_yard_field_goals_made": 'td[data-stat="fgm4"]',
    "fumbles_forced": 'td[data-stat="fumbles_forced"]',
    "fumbles_lost": 'td[data-stat="fumbles_lost"]',
    "fumbles_recovered_for_touchdown": 'td[data-stat="fumbles_rec_td"]',
    "fumbles_recovered": 'td[data-stat="fumbles_rec"]',
    "fumbles": 'td[data-stat="fumbles"]',
    "game_winning_drives": 'td[data-stat="gwd"]',
    "games_started": 'td[data-stat="gs"]',
    "games": 'td[data-stat="g"]',
    "height": 'span[itemprop="height"]',
    "interception_percentage_index": 'td[data-stat="pass_int_perc_index"]',
    "interception_percentage": 'td[data-stat="pass_int_perc"]',
    "interceptions_returned_for_touchdown": 'td[data-stat="def_int_td"]',
    "interceptions_thrown": 'td[data-stat="pass_int"]',
    "interceptions": 'td[data-stat="def_int"]',
    "kickoff_return_touchdown": 'td[data-stat="kick_ret_td"]',
    "kickoff_return_touchdowns": 'td[data-stat="kick_ret_td"]',
    "kickoff_return_yards": 'td[data-stat="kick_ret_yds"]',
    "kickoff_returns": 'td[data-stat="kick_ret"]',
    "less_than_nineteen_yards_field_goal_attempts": 'td[data-stat="fga1"]',
    "less_than_nineteen_yards_field_goals_made": 'td[data-stat="fgm1"]',
    "longest_field_goal_made": 'td[data-stat="fg_long"]',
    "longest_interception_return": 'td[data-stat="def_int_long"]',
    "longest_kickoff_return": 'td[data-stat="kick_ret_long"]',
    "longest_pass": 'td[data-stat="pass_long"]',
    "longest_punt_return": 'td[data-stat="punt_ret_long"]',
    "longest_punt": 'td[data-stat="punt_long"]',
    "longest_reception": 'td[data-stat="rec_long"]',
    "longest_rush": 'td[data-stat="rush_long"]',
    "name": 'h1[itemprop="name"]',
    "net_yards_per_attempt_index": 'td[data-stat="pass_net_yds_per_att_index"]',
    "net_yards_per_pass_attempt": 'td[data-stat="pass_net_yds_per_att"]',
    "passer_rating_index": 'td[data-stat="pass_rating_index"]',
    "passes_defended": 'td[data-stat="pass_defended"]',
    "passing_completion": 'td[data-stat="pass_cmp_perc"]',
    "passing_touchdown_percentage": 'td[data-stat="pass_td_perc"]',
    "passing_touchdowns": 'td[data-stat="pass_td"]',
    "passing_yards_per_attempt": 'td[data-stat="pass_yds_per_att"]',
    "passing_yards": 'td[data-stat="pass_yds"]',
    "position": 'td[data-stat="pos"]',
    "punt_return_touchdown": 'td[data-stat="punt_ret_td"]',
    "punt_return_touchdowns": 'td[data-stat="punt_ret_td"]',
    "punt_return_yards": 'td[data-stat="punt_ret_yds"]',
    "punt_returns": 'td[data-stat="punt_ret"]',
    "punts": 'td[data-stat="punt"]',
    "qb_record": 'td[data-stat="qb_rec"]',
    "quarterback_hits": 'td[data-stat="qb_hits"]',
    "quarterback_rating": 'td[data-stat="pass_rating"]',
    "receiving_broken_tackles": 'td[data-stat="rec_broken_tackles"]',
    "receiving_touchdowns": 'td[data-stat="rec_td"]',
    "receiving_yards_after_catch_per_reception": 'td[data-stat="rec_yac_per_rec"]',
    "receiving_yards_after_catch": 'td[data-stat="rec_yac"]',
    "receiving_yards_before_catch_per_reception": 'td[data-stat="rec_air_yds_per_rec"]',
    "receiving_yards_before_catch": 'td[data-stat="rec_air_yds"]',
    "receiving_yards_per_game": 'td[data-stat="rec_yds_per_g"]',
    "receiving_yards_per_reception": 'td[data-stat="rec_yds_per_rec"]',
    "receiving_yards": 'td[data-stat="rec_yds"]',
    "receptions_per_broken_tackle": 'td[data-stat="rec_broken_tackles_per_rec"]',
    "receptions_per_game": 'td[data-stat="rec_per_g"]',
    "receptions": 'td[data-stat="rec"]',
    "rush_attempts_per_broken_tackle": 'td[data-stat="rush_broken_tackles_per_rush"]',
    "rush_attempts_per_game": 'td[data-stat="rush_att_per_g"]',
    "rush_attempts": 'td[data-stat="rush_att"]',
    "rush_broken_tackles": 'td[data-stat="rush_broken_tackles"]',
    "rush_touchdowns": 'td[data-stat="rush_td"]',
    "rush_yards_after_contact_per_attempt": 'td[data-stat="rush_yac_per_rush"]',
    "rush_yards_after_contact": 'td[data-stat="rush_yac"]',
    "rush_yards_before_contact_per_attempt": 'td[data-stat="rush_yds_bc_per_rush"]',
    "rush_yards_before_contact": 'td[data-stat="rush_yds_before_contact"]',
    "rush_yards_per_attempt": 'td[data-stat="rush_yds_per_att"]',
    "rush_yards_per_game": 'td[data-stat="rush_yds_per_g"]',
    "rush_yards": 'td[data-stat="rush_yds"]',
    "rushing_and_receiving_touchdowns": 'td[data-stat="rush_receive_td"]',
    "sack_percentage_index": 'td[data-stat="pass_sacked_perc_index"]',
    "sack_percentage": 'td[data-stat="pass_sacked_per"]',
    "sacks": 'td[data-stat="sacks"]',
    "safeties": 'td[data-stat="safety_md"]',
    "season": 'th[data-stat="year_id"]',
    "solo_tackles": 'td[data-stat="tackles_solo"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "tackles_for_loss": 'td[data-stat="tackles_loss"]',
    "tackles": 'td[data-stat="tackles_solo"]',
    "team_abbreviation": 'td[data-stat="team"]',
    "thirty_to_thirty_nine_yard_field_goal_attempts": 'td[data-stat="fga3"]',
    "thirty_to_thirty_nine_yard_field_goals_made": 'td[data-stat="fgm3"]',
    "times_pass_target": 'td[data-stat="targets"]',
    "times_sacked": 'td[data-stat="pass_sacked"]',
    "total_punt_yards": 'td[data-stat="punt_yds"]',
    "touchdown_percentage_index": 'td[data-stat="pass_td_perc_index"]',
    "touches": 'td[data-stat="touches"]',
    "twenty_to_twenty_nine_yard_field_goal_attempts": 'td[data-stat="fga2"]',
    "twenty_to_twenty_nine_yard_field_goals_made": 'td[data-stat="fgm2"]',
    "weight": 'span[itemprop="weight"]',
    "yards_from_scrimmage": 'td[data-stat="yds_from_scrimmage"]',
    "yards_lost_from_sacks": 'td[data-stat="pass_sacked_yds"]',
    "yards_lost_to_sacks": 'td[data-stat="pass_sacked_yds"]',
    "yards_per_attempt_index": 'td[data-stat="pass_yds_per_att_index"]',
    "yards_per_completed_pass": 'td[data-stat="pass_yds_per_cmp"]',
    "yards_per_game_played": 'td[data-stat="pass_yds_per_g"]',
    "yards_per_kickoff_return": 'td[data-stat="kick_ret_yds_per_ret"]',
    "yards_per_punt_return": 'td[data-stat="punt_ret_yds_per_ret"]',
    "yards_per_punt": 'td[data-stat="punt_yds_per_punt"]',
    "yards_per_touch": 'td[data-stat="yds_per_touch"]',
    "yards_recovered_from_fumble": 'td[data-stat="fumbles_rec_yds"]',
    "yards_returned_from_interception": 'td[data-stat="def_int_yds"]',
}

DETAILED_STATS = [
    "drop_percentage",
    "dropped_passes",
    "first_downs_receiving",
    "first_downs_rushing",
    "receiving_broken_tackles",
    "receiving_yards_after_catch_per_reception",
    "receiving_yards_after_catch",
    "receiving_yards_before_catch_per_reception",
    "receiving_yards_before_catch",
    "receptions_per_broken_tackle",
    "rush_attempts_per_broken_tackle",
    "rush_broken_tackles",
    "rush_yards_after_contact_per_attempt",
    "rush_yards_after_contact",
    "rush_yards_before_contact_per_attempt",
    "rush_yards_before_contact",
]

SEASON_PAGE_URL = "http://www.pro-football-reference.com/years/%s/"

SCHEDULE_URL = "https://www.pro-football-reference.com/teams/%s/%s/gamelog/"

BOXSCORE_URL = "https://www.pro-football-reference.com/boxscores/%s.htm"

BOXSCORES_URL = "https://www.pro-football-reference.com/years/%s/week_%s.htm"
PLAYER_URL = "https://www.pro-football-reference.com/players/%s/%s.htm"
ROSTER_URL = "https://www.pro-football-reference.com/teams/%s/%s_roster.htm"

WILD_CARD = 100
DIVISION = 101
CONF_CHAMPIONSHIP = 102
SUPER_BOWL = 103

LOST_WILD_CARD = "Lost WC"
LOST_DIVISIONAL = "Lost Divisional"
LOST_CONF_CHAMPS = "Lost Conference Championship"
LOST_SUPER_BOWL = "Lost Super Bowl"
WON_SUPER_BOWL = "Won Super Bowl"
