PARSING_SCHEME = {
    "assists": 'td[data-stat="ast"]:first',
    "blocks": 'td[data-stat="blk"]:first',
    "defensive_rebounds": 'td[data-stat="drb"]:first',
    "field_goal_attempts": 'td[data-stat="fga"]:first',
    "field_goal_percentage": 'td[data-stat="fg_pct"]:first',
    "field_goals": 'td[data-stat="fg"]:first',
    "free_throw_attempts": 'td[data-stat="fta"]:first',
    "free_throw_percentage": 'td[data-stat="ft_pct"]:first',
    "free_throws": 'td[data-stat="ft"]:first',
    "games_played": 'td[data-stat="g"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "minutes_played": 'td[data-stat="mp"]:first',
    "name": "a",
    "offensive_rebounds": 'td[data-stat="orb"]:first',
    "opp_assists": 'td[data-stat="opp_ast"]:first',
    "opp_blocks": 'td[data-stat="opp_blk"]:first',
    "opp_defensive_rebounds": 'td[data-stat="opp_drb"]:first',
    "opp_field_goal_attempts": 'td[data-stat="opp_fga"]:first',
    "opp_field_goal_percentage": 'td[data-stat="opp_fg_pct"]:first',
    "opp_field_goals": 'td[data-stat="opp_fg"]:first',
    "opp_free_throw_attempts": 'td[data-stat="opp_fta"]:first',
    "opp_free_throw_percentage": 'td[data-stat="opp_ft_pct"]:first',
    "opp_free_throws": 'td[data-stat="opp_ft"]:first',
    "opp_minutes_played": 'td[data-stat="mp"]:first',
    "opp_offensive_rebounds": 'td[data-stat="opp_orb"]:first',
    "opp_personal_fouls": 'td[data-stat="opp_pf"]:first',
    "opp_points": 'td[data-stat="opp_pts"]:first',
    "opp_steals": 'td[data-stat="opp_stl"]:first',
    "opp_three_point_field_goal_attempts": 'td[data-stat="opp_fg3a"]:first',
    "opp_three_point_field_goal_percentage": 'td[data-stat="opp_fg3_pct"]:first',
    "opp_three_point_field_goals": 'td[data-stat="opp_fg3"]:first',
    "opp_total_rebounds": 'td[data-stat="opp_trb"]:first',
    "opp_turnovers": 'td[data-stat="opp_tov"]:first',
    "opp_two_point_field_goal_attempts": 'td[data-stat="opp_fg2a"]:first',
    "opp_two_point_field_goal_percentage": 'td[data-stat="opp_fg2_pct"]:first',
    "opp_two_point_field_goals": 'td[data-stat="opp_fg2"]:first',
    "personal_fouls": 'td[data-stat="pf"]:first',
    "points": 'td[data-stat="pts"]:first',
    "steals": 'td[data-stat="stl"]:first',
    "three_point_field_goal_attempts": 'td[data-stat="fg3a"]:first',
    "three_point_field_goal_percentage": 'td[data-stat="fg3_pct"]:first',
    "three_point_field_goals": 'td[data-stat="fg3"]:first',
    "total_rebounds": 'td[data-stat="trb"]:first',
    "turnovers": 'td[data-stat="tov"]:first',
    "two_point_field_goal_attempts": 'td[data-stat="fg2a"]:first',
    "two_point_field_goal_percentage": 'td[data-stat="fg2_pct"]:first',
    "two_point_field_goals": 'td[data-stat="fg2"]:first',
    "win_percentage": 'td[data-stat="win_loss_pct"]:first',
    "wins": 'td[data-stat="wins"]:first',
}

SCHEDULE_SCHEME = {
    "boxscore": 'td[data-stat="box_score_text"]:first',
    "date": 'td[data-stat="date_game"]:first',
    "game": 'th[data-stat="g"]:first',
    "location": 'td[data-stat="game_location"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "opponent_abbr": 'td[data-stat="opp_id"]:first',
    "opponent_name": 'td[data-stat="opp_name"]:first',
    "points_allowed": 'td[data-stat="opp_pts"]:first',
    "points_scored": 'td[data-stat="pts"]:first',
    "result": 'td[data-stat="game_result"]:first',
    "streak": 'td[data-stat="game_streak"]:first',
    "time": 'td[data-stat="game_start_time"]:first',
    "wins": 'td[data-stat="wins"]:first',
}

BOXSCORE_SCHEME = {
    "away_assist_percentage": 'tfoot td[data-stat="ast_pct"]',
    "away_assists": 'tfoot td[data-stat="ast"]',
    "away_block_percentage": 'tfoot td[data-stat="blk_pct"]',
    "away_blocks": 'tfoot td[data-stat="blk"]',
    "away_defensive_rating": 'tfoot td[data-stat="def_rtg"]',
    "away_defensive_rebound_percentage": 'tfoot td[data-stat="drb_pct"]',
    "away_defensive_rebounds": 'tfoot td[data-stat="drb"]',
    "away_effective_field_goal_percentage": 'tfoot td[data-stat="efg_pct"]',
    "away_field_goal_attempts": 'tfoot td[data-stat="fga"]',
    "away_field_goal_percentage": 'tfoot td[data-stat="fg_pct"]',
    "away_field_goals": 'tfoot td[data-stat="fg"]',
    "away_free_throw_attempt_rate": 'tfoot td[data-stat="fta_per_fga_pct"]',
    "away_free_throw_attempts": 'tfoot td[data-stat="fta"]',
    "away_free_throw_percentage": 'tfoot td[data-stat="ft_pct"]',
    "away_free_throws": 'tfoot td[data-stat="ft"]',
    "away_minutes_played": 'tfoot td[data-stat="mp"]',
    "away_name": 'div[class="scorebox"] a[href*="/teams"]',
    "away_offensive_rating": 'tfoot td[data-stat="off_rtg"]',
    "away_offensive_rebound_percentage": 'tfoot td[data-stat="orb_pct"]',
    "away_offensive_rebounds": 'tfoot td[data-stat="orb"]',
    "away_personal_fouls": 'tfoot td[data-stat="pf"]',
    "away_points": 'tfoot td[data-stat="pts"]',
    "away_record": 'div[class="scores"] + div',
    "away_steal_percentage": 'tfoot td[data-stat="stl_pct"]',
    "away_steals": 'tfoot td[data-stat="stl"]',
    "away_three_point_attempt_rate": 'tfoot td[data-stat="fg3a_per_fga_pct"]',
    "away_three_point_field_goal_attempts": 'tfoot td[data-stat="fg3a"]',
    "away_three_point_field_goal_percentage": 'tfoot td[data-stat="fg3_pct"]',
    "away_three_point_field_goals": 'tfoot td[data-stat="fg3"]',
    "away_total_rebound_percentage": 'tfoot td[data-stat="trb_pct"]',
    "away_total_rebounds": 'tfoot td[data-stat="trb"]',
    "away_true_shooting_percentage": 'tfoot td[data-stat="ts_pct"]',
    "away_turnover_percentage": 'tfoot td[data-stat="tov_pct"]',
    "away_turnovers": 'tfoot td[data-stat="tov"]',
    "away_two_point_field_goal_attempts": 'tfoot td[data-stat="fg2a"]',
    "away_two_point_field_goal_percentage": 'tfoot td[data-stat="fg2_pct"]',
    "away_two_point_field_goals": 'tfoot td[data-stat="fg2"]',
    "date": 'div[class="scorebox_meta"]',
    "home_assist_percentage": 'tfoot td[data-stat="ast_pct"]',
    "home_assists": 'tfoot td[data-stat="ast"]',
    "home_block_percentage": 'tfoot td[data-stat="blk_pct"]',
    "home_blocks": 'tfoot td[data-stat="blk"]',
    "home_defensive_rating": 'tfoot td[data-stat="def_rtg"]',
    "home_defensive_rebound_percentage": 'tfoot td[data-stat="drb_pct"]',
    "home_defensive_rebounds": 'tfoot td[data-stat="drb"]',
    "home_effective_field_goal_percentage": 'tfoot td[data-stat="efg_pct"]',
    "home_field_goal_attempts": 'tfoot td[data-stat="fga"]',
    "home_field_goal_percentage": 'tfoot td[data-stat="fg_pct"]',
    "home_field_goals": 'tfoot td[data-stat="fg"]',
    "home_free_throw_attempt_rate": 'tfoot td[data-stat="fta_per_fga_pct"]',
    "home_free_throw_attempts": 'tfoot td[data-stat="fta"]',
    "home_free_throw_percentage": 'tfoot td[data-stat="ft_pct"]',
    "home_free_throws": 'tfoot td[data-stat="ft"]',
    "home_minutes_played": 'tfoot td[data-stat="mp"]',
    "home_name": 'div[class="scorebox"] a[href*="/teams"]',
    "home_offensive_rating": 'tfoot td[data-stat="off_rtg"]',
    "home_offensive_rebound_percentage": 'tfoot td[data-stat="orb_pct"]',
    "home_offensive_rebounds": 'tfoot td[data-stat="orb"]',
    "home_personal_fouls": 'tfoot td[data-stat="pf"]',
    "home_points": 'div[class="score"]',
    "home_record": 'div[class="scores"] + div',
    "home_steal_percentage": 'tfoot td[data-stat="stl_pct"]',
    "home_steals": 'tfoot td[data-stat="stl"]',
    "home_three_point_attempt_rate": 'tfoot td[data-stat="fg3a_per_fga_pct"]',
    "home_three_point_field_goal_attempts": 'tfoot td[data-stat="fg3a"]',
    "home_three_point_field_goal_percentage": 'tfoot td[data-stat="fg3_pct"]',
    "home_three_point_field_goals": 'tfoot td[data-stat="fg3"]',
    "home_total_rebound_percentage": 'tfoot td[data-stat="trb_pct"]',
    "home_total_rebounds": 'tfoot td[data-stat="trb"]',
    "home_true_shooting_percentage": 'tfoot td[data-stat="ts_pct"]',
    "home_turnover_percentage": 'tfoot td[data-stat="tov_pct"]',
    "home_turnovers": 'tfoot td[data-stat="tov"]',
    "home_two_point_field_goal_attempts": 'tfoot td[data-stat="fg2a"]',
    "home_two_point_field_goal_percentage": 'tfoot td[data-stat="fg2_pct"]',
    "home_two_point_field_goals": 'tfoot td[data-stat="fg2"]',
    "location": 'div[class="scorebox_meta"]',
    "losing_abbr": "",
    "losing_name": "",
    "pace": 'td[data-stat="pace"]:first',
    "summary": "table#line_score",
    "winning_abbr": "",
    "winning_name": "",
}

BOXSCORE_ELEMENT_INDEX = {
    "away_name": 0,
    "date": 0,
    "home_assist_percentage": 7,
    "home_assists": 7,
    "home_block_percentage": 7,
    "home_blocks": 7,
    "home_defensive_rating": 7,
    "home_defensive_rebound_percentage": 7,
    "home_defensive_rebounds": 7,
    "home_effective_field_goal_percentage": 7,
    "home_field_goal_attempts": 7,
    "home_field_goal_percentage": 7,
    "home_field_goals": 7,
    "home_free_throw_attempt_rate": 7,
    "home_free_throw_attempts": 7,
    "home_free_throw_percentage": 7,
    "home_free_throws": 7,
    "home_minutes_played": 7,
    "home_name": 1,
    "home_offensive_rating": 7,
    "home_offensive_rebound_percentage": 7,
    "home_offensive_rebounds": 7,
    "home_personal_fouls": 7,
    "home_points": -1,
    "home_record": -1,
    "home_steal_percentage": 7,
    "home_steals": 7,
    "home_three_point_attempt_rate": 7,
    "home_three_point_field_goal_attempts": 7,
    "home_three_point_field_goal_percentage": 7,
    "home_three_point_field_goals": 7,
    "home_total_rebound_percentage": 7,
    "home_total_rebounds": 7,
    "home_true_shooting_percentage": 7,
    "home_turnover_percentage": 7,
    "home_turnovers": 7,
    "home_two_point_field_goal_attempts": 7,
    "home_two_point_field_goal_percentage": 7,
    "home_two_point_field_goals": 7,
    "location": 1,
}

PLAYER_SCHEME = {
    "age": "nobr",
    "and_ones": 'td[data-stat="and1s"]',
    "assist_percentage": 'td[data-stat="ast_pct"]',
    "assists_per_poss": 'td[data-stat="ast_per_poss"]',
    "assists": 'td[data-stat="ast"]',
    "birth_date": 'td[data-stat=""]',
    "block_percentage": 'td[data-stat="blk_pct"]',
    "blocking_fouls": 'td[data-stat="fouls_blocking"]',
    "blocks_per_poss": 'td[data-stat="blk_per_poss"]',
    "blocks": 'td[data-stat="blk"]',
    "box_plus_minus": 'td[data-stat="bpm"]',
    "boxscore_box_plus_minus": 'td[data-stat="plus_minus"]',
    "center_percentage": 'td[data-stat="pct_5"]',
    "defensive_box_plus_minus": 'td[data-stat="dbpm"]',
    "defensive_rating": 'td[data-stat="def_rtg"]',
    "defensive_rebound_percentage": 'td[data-stat="drb_pct"]',
    "defensive_rebounds_per_poss": 'td[data-stat="drb_per_poss"]',
    "defensive_rebounds": 'td[data-stat="drb"]',
    "defensive_win_shares": 'td[data-stat="dws"]',
    "dunks": 'td[data-stat="fg2_dunk"]',
    "effective_field_goal_percentage": 'td[data-stat="efg_pct"]',
    "field_goal_attempts_per_poss": 'td[data-stat="fga_per_poss"]',
    "field_goal_attempts": 'td[data-stat="fga"]',
    "field_goal_perc_sixteen_foot_plus_two_pointers": 'td[data-stat="fg_pct_16_xx"]',
    "field_goal_perc_ten_to_sixteen_feet": 'td[data-stat="fg_pct_10_16"]',
    "field_goal_perc_three_to_ten_feet": 'td[data-stat="fg_pct_03_10"]',
    "field_goal_perc_zero_to_three_feet": 'td[data-stat="fg_pct_00_03"]',
    "field_goal_percentage": 'td[data-stat="fg_pct"]',
    "field_goals_per_poss": 'td[data-stat="fg_per_poss"]',
    "field_goals": 'td[data-stat="fg"]',
    "free_throw_attempt_rate": 'td[data-stat="fta_per_fga_pct"]',
    "free_throw_attempts_per_poss": 'td[data-stat="fta_per_poss"]',
    "free_throw_attempts": 'td[data-stat="fta"]',
    "free_throw_percentage": 'td[data-stat="ft_pct"]',
    "free_throws_per_poss": 'td[data-stat="ft_per_poss"]',
    "free_throws": 'td[data-stat="ft"]',
    "games_played": 'td[data-stat="g"]',
    "games_started": 'td[data-stat="gs"]',
    "half_court_heaves_made": 'td[data-stat="fg3_heave"]',
    "half_court_heaves": 'td[data-stat="fg3a_heave"]',
    "height": 'span[itemprop="height"]',
    "lost_ball_turnovers": 'td[data-stat="tov_lost_ball"]',
    "minutes_played": 'td[data-stat="mp"]',
    "name": "h1",
    "nationality": 'td[data-stat=""]',
    "net_plus_minus": 'td[data-stat="plus_minus_net"]',
    "offensive_box_plus_minus": 'td[data-stat="obpm"]',
    "offensive_fouls": 'td[data-stat="fouls_offensive"]',
    "offensive_rating": 'td[data-stat="off_rtg"]',
    "offensive_rebound_percentage": 'td[data-stat="orb_pct"]',
    "offensive_rebounds_per_poss": 'td[data-stat="orb_per_poss"]',
    "offensive_rebounds": 'td[data-stat="orb"]',
    "offensive_win_shares": 'td[data-stat="ows"]',
    "on_court_plus_minus": 'td[data-stat="plus_minus_on"]',
    "other_turnovers": 'td[data-stat="tov_other"]',
    "passing_turnovers": 'td[data-stat="tov_bad_pass"]',
    "percentage_field_goals_as_dunks": 'td[data-stat="pct_fg2_dunk"]',
    "percentage_of_three_pointers_from_corner": 'td[data-stat="pct_fg3a_corner"]',
    "percentage_shots_three_pointers": 'td[data-stat="fg3a_pct_fga"]',
    "percentage_shots_two_pointers": 'td[data-stat="fg2a_pct_fga"]',
    "percentage_sixteen_foot_plus_two_pointers": 'td[data-stat="pct_fga_16_xx"]',
    "percentage_ten_to_sixteen_footers": 'td[data-stat="pct_fga_10_16"]',
    "percentage_three_to_ten_footers": 'td[data-stat="pct_fga_03_10"]',
    "percentage_zero_to_three_footers": 'td[data-stat="pct_fga_00_03"]',
    "personal_fouls_per_poss": 'td[data-stat="pf_per_poss"]',
    "personal_fouls": 'td[data-stat="pf"]',
    "player_efficiency_rating": 'td[data-stat="per"]',
    "point_guard_percentage": 'td[data-stat="pct_1"]',
    "points_generated_by_assists": 'td[data-stat="astd_pts"]',
    "points_per_poss": 'td[data-stat="pts_per_poss"]',
    "points": 'td[data-stat="pts"]',
    "position": 'td[data-stat="pos"]',
    "power_forward_percentage": 'td[data-stat="pct_4"]',
    "salary": 'td[data-stat="salary"]',
    "season": 'th[data-stat="season"]:first',
    "shooting_distance": 'td[data-stat="avg_dist"]',
    "shooting_fouls_drawn": 'td[data-stat="drawn_shooting"]',
    "shooting_fouls": 'td[data-stat="fouls_shooting"]',
    "shooting_guard_percentage": 'td[data-stat="pct_2"]',
    "shots_blocked": 'td[data-stat="fga_blkd"]',
    "small_forward_percentage": 'td[data-stat="pct_3"]',
    "steal_percentage": 'td[data-stat="stl_pct"]',
    "steals_per_poss": 'td[data-stat="stl_per_poss"]',
    "steals": 'td[data-stat="stl"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "take_fouls": 'td[data-stat="fouls_take"]',
    "team_abbreviation": 'td[data-stat="team_id"]',
    "three_point_attempt_rate": 'td[data-stat="fg3a_per_fga_pct"]',
    "three_point_attempts_per_poss": 'td[data-stat="fg3a_per_poss"]',
    "three_point_attempts": 'td[data-stat="fg3a"]',
    "three_point_percentage": 'td[data-stat="fg3_pct"]',
    "three_point_shot_percentage_from_corner": 'td[data-stat="fg3_pct_corner"]',
    "three_pointers_assisted_percentage": 'td[data-stat="fg3_pct_ast"]',
    "three_pointers_per_poss": 'td[data-stat="fg3_per_poss"]',
    "three_pointers": 'td[data-stat="fg3"]',
    "total_rebound_percentage": 'td[data-stat="trb_pct"]',
    "total_rebounds_per_poss": 'td[data-stat="trb_per_poss"]',
    "total_rebounds": 'td[data-stat="trb"]',
    "true_shooting_percentage": 'td[data-stat="ts_pct"]',
    "turnover_percentage": 'td[data-stat="tov_pct"]',
    "turnovers_per_poss": 'td[data-stat="tov_per_poss"]',
    "turnovers": 'td[data-stat="tov"]',
    "two_point_attempts_per_poss": 'td[data-stat="fg2a_per_poss"]',
    "two_point_attempts": 'td[data-stat="fg2a"]',
    "two_point_percentage": 'td[data-stat="fg2_pct"]',
    "two_pointers_assisted_percentage": 'td[data-stat="fg2_pct_ast"]',
    "two_pointers_per_poss": 'td[data-stat="fg2_per_poss"]',
    "two_pointers": 'td[data-stat="fg2"]',
    "usage_percentage": 'td[data-stat="usg_pct"]',
    "value_over_replacement_player": 'td[data-stat="vorp"]',
    "weight": 'span[itemprop="weight"]',
    "win_shares_per_48_minutes": 'td[data-stat="ws_per_48"]',
    "win_shares": 'td[data-stat="ws"]',
}

NATIONALITY = {
    "ag": "Antigua and Barbuda",
    "ao": "Angola",
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "ba": "Bosnia and Herzegovina",
    "be": "Belgium",
    "bg": "Bulgaria",
    "br": "Brazil",
    "bs": "Bahamas",
    "ca": "Canada",
    "cd": "Democratic Replubic of Congo",
    "cg": "Republic of Congo",
    "ch": "Switzerland",
    "cm": "Cameroon",
    "cn": "China",
    "co": "Colombia",
    "cu": "Cuba",
    "cv": "Cape Verde",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "dm": "Dominica",
    "do": "Dominican Replubic",
    "ee": "Estonia",
    "eg": "Egypt",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "ga": "Gabon",
    "gb": "United Kingdom",
    "ge": "Georgia",
    "gf": "French Guiana",
    "gh": "Ghana",
    "gn": "Guinea",
    "gp": "Guadeloupe",
    "gr": "Greece",
    "gy": "Guyana",
    "hr": "Croatia",
    "ht": "Haiti",
    "hu": "Hungary",
    "ie": "Ireland",
    "il": "Israel",
    "ir": "Islamic Replubic of Iran",
    "is": "Iceland",
    "it": "Italy",
    "jm": "Jamaica",
    "jp": "Japan",
    "ke": "Kenya",
    "kr": "Republic of Korea",
    "lb": "Lebanon",
    "lc": "Saint Lucia",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "lv": "Latvia",
    "ma": "Morocco",
    "me": "Montenegro",
    "mk": "Republic of Macedonia",
    "ml": "Mali",
    "mq": "Martinique",
    "mx": "Mexico",
    "ng": "Nigeria",
    "nl": "Netherlands",
    "no": "Norway",
    "nz": "New Zealand",
    "pa": "Panama",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "ro": "Romania",
    "rs": "Serbia",
    "ru": "Russian Federation",
    "sd": "Sudan",
    "se": "Sweden",
    "si": "Slovenia",
    "sk": "Slovakia",
    "sn": "Senegal",
    "ss": "South Sudan",
    "td": "Chad",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tt": "Trinidad and Tobago",
    "tw": "Taiwan",
    "tz": "United Republic of Tanzania",
    "ua": "Ukraine",
    "us": "United States of America",
    "uy": "Uruguay",
    "vc": "Saint Vincent and the Grenadines",
    "ve": "Venezuela",
    "vi": "U.S. Virgin Islands",
    "za": "South Africa",
}

SEASON_PAGE_URL = "http://www.basketball-reference.com/leagues/NBA_%s.html"

SCHEDULE_URL = "http://www.basketball-reference.com/teams/%s/%s_games.html"

BOXSCORE_URL = "https://www.basketball-reference.com/boxscores/%s.html"

BOXSCORES_URL = "https://www.basketball-reference.com/boxscores/?month=%s&day=%s&year=%s"

PLAYER_URL = "https://www.basketball-reference.com/players/%s/%s.html"

ROSTER_URL = "https://www.basketball-reference.com/teams/%s/%s.html"
