PARSING_SCHEME = {
    "at_bats": 'td[data-stat="AB"]:first',
    "average_batter_age": 'td[data-stat="age_bat"]:first',
    "average_pitcher_age": 'td[data-stat="age_pitch"]:first',
    "away_record": 'td[data-stat="record_road"]:first',
    "balks": 'td[data-stat="BK"]:first',
    "bases_on_balls": 'td[data-stat="BB"]:first',
    "bases_on_walks_given_per_nine_innings": 'td[data-stat="bases_on_balls_per_nine"]:first',
    "bases_on_walks_given": 'td[data-stat="BB"]:first',
    "batters_faced": 'td[data-stat="batters_faced"]:first',
    "batting_average": 'td[data-stat="batting_avg"]:first',
    "complete_game_shutouts": 'td[data-stat="SHO_cg"]:first',
    "complete_games": 'td[data-stat="CG"]:first',
    "doubles": 'td[data-stat="2B"]:first',
    "earned_runs_against_plus": 'td[data-stat="earned_run_avg_plus"]:first',
    "earned_runs_against": 'td[data-stat="earned_run_avg"]:first',
    "extra_inning_record": 'td[data-stat="record_xinn"]:first',
    "fielding_independent_pitching": 'td[data-stat="fip"]:first',
    "games_finished": 'td[data-stat="GF"]:first',
    "games": 'td[data-stat="G"]:first',
    "grounded_into_double_plays": 'td[data-stat="GIDP"]:first',
    "hit_pitcher": 'td[data-stat="HBP"]:first',
    "hits_allowed": 'td[data-stat="H"]:first',
    "hits_per_nine_innings": 'td[data-stat="hits_per_nine"]:first',
    "hits": 'td[data-stat="H"]:first',
    "home_record": 'td[data-stat="record_home"]:first',
    "home_runs_against": 'td[data-stat="HR"]:first',
    "home_runs_per_nine_innings": 'td[data-stat="home_runs_per_nine"]:first',
    "home_runs": 'td[data-stat="HR"]:first',
    "innings_pitched": 'td[data-stat="IP"]:first',
    "intentional_bases_on_balls": 'td[data-stat="IBB"]:first',
    "interleague_record": 'td[data-stat="record_interleague"]:first',
    "last_ten_games_record": 'td[data-stat="record_last_10"]:first',
    "last_thirty_games_record": 'td[data-stat="record_last_30"]:first',
    "last_twenty_games_record": 'td[data-stat="record_last_20"]:first',
    "league": 'td[data-stat="lg_ID"]:first',
    "losses": 'td[data-stat="L"]:first',
    "luck": 'td[data-stat="luck_pythag"]:first',
    "name": "a",
    "number_of_pitchers": 'td[data-stat="pitchers_used"]:first',
    "number_players_used": 'td[data-stat="batters_used"]:first',
    "on_base_percentage": 'td[data-stat="onbase_perc"]:first',
    "on_base_plus_slugging_percentage_plus": 'td[data-stat="onbase_plus_slugging_plus"]:first',
    "on_base_plus_slugging_percentage": 'td[data-stat="onbase_plus_slugging"]:first',
    "opposing_runners_left_on_base": 'td[data-stat="LOB"]:first',
    "plate_appearances": 'td[data-stat="PA"]:first',
    "pythagorean_win_loss": 'td[data-stat="record_pythag"]:first',
    "record_vs_left_handed_pitchers": 'td[data-stat="record_vs_lhp"]:first',
    "record_vs_right_handed_pitchers": 'td[data-stat="record_vs_rhp"]:first',
    "record_vs_teams_over_500": 'td[data-stat="record_vs_over_500"]:first',
    "record_vs_teams_under_500": 'td[data-stat="record_vs_under_500"]:first',
    "run_difference": 'td[data-stat="run_diff"]:first',
    "runners_left_on_base": 'td[data-stat="LOB"]:first',
    "runs_against": 'td[data-stat="RA"]:first',
    "runs_allowed_per_game": 'td[data-stat="runs_allowed_per_game"]:first',
    "runs_batted_in": 'td[data-stat="RBI"]:first',
    "runs": 'td[data-stat="R"]:first',
    "sacrifice_flies": 'td[data-stat="SF"]:first',
    "sacrifice_hits": 'td[data-stat="SH"]:first',
    "saves": 'td[data-stat="SV"]:first',
    "shutouts": 'td[data-stat="SHO_team"]:first',
    "simple_rating_system": 'td[data-stat="simple_rating_system"]:first',
    "single_run_record": 'td[data-stat="record_one_run"]:first',
    "slugging_percentage": 'td[data-stat="slugging_perc"]:first',
    "stolen_bases": 'td[data-stat="SB"]:first',
    "streak": 'td[data-stat="winning_streak"]:first',
    "strength_of_schedule": 'td[data-stat="strength_of_schedule"]:first',
    "strikeouts_per_base_on_balls": 'td[data-stat="strikeouts_per_base_on_balls"]:first',
    "strikeouts_per_nine_innings": 'td[data-stat="strikeouts_per_nine"]:first',
    "strikeouts": 'td[data-stat="SO"]:first',
    "times_caught_stealing": 'td[data-stat="CS"]:first',
    "times_hit_by_pitch": 'td[data-stat="HBP"]:first',
    "times_struck_out": 'td[data-stat="SO"]:first',
    "total_bases": 'td[data-stat="TB"]:first',
    "total_runs": 'td[data-stat="R"]:first',
    "triples": 'td[data-stat="3B"]:first',
    "whip": 'td[data-stat="whip"]:first',
    "wild_pitches": 'td[data-stat="WP"]:first',
    "win_percentage": 'td[data-stat="win_loss_perc"]:first',
    "wins": 'td[data-stat="W"]:first',
}

TEAM_ELEMENT = {
    "away_losses": 1,
    "away_wins": 0,
    "extra_inning_losses": 1,
    "extra_inning_wins": 0,
    "home_losses": 1,
    "home_wins": 0,
    "losses_last_ten_games": 1,
    "losses_last_thirty_games": 1,
    "losses_last_twenty_games": 1,
    "losses_vs_left_handed_pitchers": 1,
    "losses_vs_right_handed_pitchers": 1,
    "losses_vs_teams_over_500": 1,
    "losses_vs_teams_under_500": 1,
    "single_run_losses": 1,
    "single_run_wins": 0,
    "wins_last_ten_games": 0,
    "wins_last_thirty_games": 0,
    "wins_last_twenty_games": 0,
    "wins_vs_left_handed_pitchers": 0,
    "wins_vs_right_handed_pitchers": 0,
    "wins_vs_teams_over_500": 0,
    "wins_vs_teams_under_500": 0,
}

SCHEDULE_SCHEME = {
    "attendance": 'td[data-stat="attendance"]:first',
    "date": 'td[data-stat="date_game"]:first',
    "day_or_night": 'td[data-stat="day_or_night"]:first',
    "game_duration": 'td[data-stat="time_of_game"]:first',
    "game": 'th[data-stat="team_game"]:first',
    "games_behind": 'td[data-stat="games_back"]:first',
    "innings": 'td[data-stat="extra_innings"]:first',
    "location": 'td[data-stat="homeORvis"]:first',
    "loser": 'td[data-stat="losing_pitcher"]:first',
    "opponent_abbr": 'td[data-stat="opp_ID"]:first',
    "rank": 'td[data-stat="rank"]:first',
    "record": 'td[data-stat="win_loss_record"]:first',
    "result": 'td[data-stat="win_loss_result"]:first',
    "runs_allowed": 'td[data-stat="RA"]:first',
    "runs_scored": 'td[data-stat="R"]:first',
    "save": 'td[data-stat="saving_pitcher"]:first',
    "streak": 'td[data-stat="win_loss_streak"]:first',
    "winner": 'td[data-stat="winning_pitcher"]:first',
}

ELEMENT_INDEX = {
    "bases_on_walks_given": 1,
    "hits_allowed": 1,
    "home_runs_against": 1,
    "opposing_runners_left_on_base": 1,
    "strikeouts": 1,
    "total_runs": 1,
}

BOXSCORE_SCHEME = {
    "away_assists": 'tfoot td[data-stat="A"]',
    "away_at_bats": 'tfoot td[data-stat="AB"]',
    "away_average_leverage_index": 'tfoot td[data-stat="leverage_index_avg"]',
    "away_base_out_runs_added": 'tfoot td[data-stat="re24_bat"]',
    "away_base_out_runs_saved": 'tfoot td[data-stat="re24_def"]',
    "away_bases_on_balls": 'tfoot td[data-stat="BB"]',
    "away_batting_average": 'tfoot td[data-stat="batting_avg"]',
    "away_earned_runs": 'tfoot td[data-stat="earned_run_avg"]',
    "away_fly_balls": 'tfoot td[data-stat="inplay_fb_total"]',
    "away_game_score": 'tfoot td[data-stat="game_score"]',
    "away_grounded_balls": 'tfoot td[data-stat="inplay_gb_total"]',
    "away_hits": 'tfoot td[data-stat="H"]',
    "away_home_runs": 'tfoot td[data-stat="HR"]',
    "away_inherited_runners": 'tfoot td[data-stat="inherited_runners"]',
    "away_inherited_score": 'tfoot td[data-stat="inherited_score"]',
    "away_innings_pitched": 'tfoot td[data-stat="IP"]',
    "away_line_drives": 'tfoot td[data-stat="inplay_ld"]',
    "away_name": 'a[itemprop="name"]:first',
    "away_on_base_percentage": 'tfoot td[data-stat="onbase_perc"]',
    "away_on_base_plus": 'tfoot td[data-stat="onbase_plus_slugging"]',
    "away_pitches": 'tfoot td[data-stat="pitches"]',
    "away_plate_appearances": 'tfoot td[data-stat="PA"]',
    "away_putouts": 'tfoot td[data-stat="PO"]',
    "away_rbi": 'tfoot td[data-stat="RBI"]',
    "away_runs": 'tfoot td[data-stat="R"]',
    "away_slugging_percentage": 'tfoot td[data-stat="slugging_perc"]',
    "away_strikeouts": 'tfoot td[data-stat="SO"]',
    "away_strikes_by_contact": 'tfoot td[data-stat="strikes_contact"]',
    "away_strikes_looking": 'tfoot td[data-stat="strikes_looking"]',
    "away_strikes_swinging": 'tfoot td[data-stat="strikes_swinging"]',
    "away_strikes": 'tfoot td[data-stat="strikes_total"]',
    "away_unknown_bat_type": 'tfoot td[data-stat="inplay_unk"]',
    "away_win_probability_added": 'tfoot td[data-stat="wpa_bat_pos"]',
    "away_win_probability_by_pitcher": 'tfoot td[data-stat="wpa_def"]',
    "away_win_probability_for_offensive_player": 'tfoot td[data-stat="wpa_bat"]',
    "away_win_probability_subtracted": 'tfoot td[data-stat="wpa_bat_neg"]',
    "game_info": 'div[class="scorebox_meta"]',
    "home_assists": 'tfoot td[data-stat="A"]',
    "home_at_bats": 'tfoot td[data-stat="AB"]',
    "home_average_leverage_index": 'tfoot td[data-stat="leverage_index_avg"]',
    "home_base_out_runs_added": 'tfoot td[data-stat="re24_bat"]',
    "home_base_out_runs_saved": 'tfoot td[data-stat="re24_def"]',
    "home_bases_on_balls": 'tfoot td[data-stat="BB"]',
    "home_batting_average": 'tfoot td[data-stat="batting_avg"]',
    "home_earned_runs": 'tfoot td[data-stat="earned_run_avg"]',
    "home_fly_balls": 'tfoot td[data-stat="inplay_fb_total"]',
    "home_game_score": 'tfoot td[data-stat="game_score"]',
    "home_grounded_balls": 'tfoot td[data-stat="inplay_gb_total"]',
    "home_hits": 'tfoot td[data-stat="H"]',
    "home_home_runs": 'tfoot td[data-stat="HR"]',
    "home_inherited_runners": 'tfoot td[data-stat="inherited_runners"]',
    "home_inherited_score": 'tfoot td[data-stat="inherited_score"]',
    "home_innings_pitched": 'tfoot td[data-stat="IP"]',
    "home_line_drives": 'tfoot td[data-stat="inplay_ld"]',
    "home_name": 'a[itemprop="name"]:last',
    "home_on_base_percentage": 'tfoot td[data-stat="onbase_perc"]',
    "home_on_base_plus": 'tfoot td[data-stat="onbase_plus_slugging"]',
    "home_pitches": 'tfoot td[data-stat="pitches"]',
    "home_plate_appearances": 'tfoot td[data-stat="PA"]',
    "home_putouts": 'tfoot td[data-stat="PO"]',
    "home_rbi": 'tfoot td[data-stat="RBI"]',
    "home_runs": 'tfoot td[data-stat="R"]',
    "home_slugging_percentage": 'tfoot td[data-stat="slugging_perc"]',
    "home_strikeouts": 'tfoot td[data-stat="SO"]',
    "home_strikes_by_contact": 'tfoot td[data-stat="strikes_contact"]',
    "home_strikes_looking": 'tfoot td[data-stat="strikes_looking"]',
    "home_strikes_swinging": 'tfoot td[data-stat="strikes_swinging"]',
    "home_strikes": 'tfoot td[data-stat="strikes_total"]',
    "home_unknown_bat_type": 'tfoot td[data-stat="inplay_unk"]',
    "home_win_probability_added": 'tfoot td[data-stat="wpa_bat_pos"]',
    "home_win_probability_by_pitcher": 'tfoot td[data-stat="wpa_def"]',
    "home_win_probability_for_offensive_player": 'tfoot td[data-stat="wpa_bat"]',
    "home_win_probability_subtracted": 'tfoot td[data-stat="wpa_bat_neg"]',
    "losing_abbr": 'td[data-stat=""]',
    "losing_name": 'td[data-stat=""]',
    "summary": 'table[class="linescore nohover stats_table no_freeze"]',
    "winner": 'td[data-stat=""]',
    "winning_abbr": 'td[data-stat=""]',
    "winning_name": 'td[data-stat=""]',
}

BOXSCORE_ELEMENT_INDEX = {
    "attendance": 2,
    "away_assists": 0,
    "away_at_bats": 0,
    "away_average_leverage_index": 1,
    "away_base_out_runs_added": 0,
    "away_base_out_runs_saved": 0,
    "away_bases_on_balls": 0,
    "away_batting_average": 0,
    "away_earned_runs": 1,
    "away_fly_balls": 1,
    "away_game_score": 0,
    "away_grounded_balls": 1,
    "away_hits": 0,
    "away_home_runs": 0,
    "away_inherited_runners": 0,
    "away_inherited_score": 0,
    "away_innings_pitched": 0,
    "away_line_drives": 1,
    "away_on_base_percentage": 0,
    "away_on_base_plus": 0,
    "away_pitches": 1,
    "away_plate_appearances": 0,
    "away_putouts": 0,
    "away_rbi": 0,
    "away_runs": 0,
    "away_slugging_percentage": 0,
    "away_strikeouts": 0,
    "away_strikes_by_contact": 1,
    "away_strikes_looking": 1,
    "away_strikes_swinging": 1,
    "away_strikes": 0,
    "away_unknown_bat_type": 1,
    "away_win_probability_added": 0,
    "away_win_probability_by_pitcher": 0,
    "away_win_probability_for_offensive_player": 0,
    "away_win_probability_subtracted": 0,
    "date": 0,
    "duration": 4,
    "home_assists": 1,
    "home_at_bats": 1,
    "home_average_leverage_index": 0,
    "home_base_out_runs_added": 1,
    "home_base_out_runs_saved": 1,
    "home_bases_on_balls": 1,
    "home_batting_average": 1,
    "home_earned_runs": 0,
    "home_fly_balls": 0,
    "home_game_score": 1,
    "home_grounded_balls": 0,
    "home_hits": 1,
    "home_home_runs": 1,
    "home_inherited_runners": 1,
    "home_inherited_score": 1,
    "home_innings_pitched": 1,
    "home_line_drives": 0,
    "home_on_base_percentage": 1,
    "home_on_base_plus": 1,
    "home_pitches": 0,
    "home_plate_appearances": 1,
    "home_putouts": 1,
    "home_rbi": 1,
    "home_runs": 1,
    "home_slugging_percentage": 1,
    "home_strikeouts": 1,
    "home_strikes_by_contact": 0,
    "home_strikes_looking": 0,
    "home_strikes_swinging": 0,
    "home_strikes": 1,
    "home_unknown_bat_type": 0,
    "home_win_probability_added": 1,
    "home_win_probability_by_pitcher": 1,
    "home_win_probability_for_offensive_player": 1,
    "home_win_probability_subtracted": 1,
    "time_of_day": 5,
    "time": 1,
    "venue": 3,
}

PLAYER_SCHEME = {
    "assists": 'td[data-stat="A"]',
    "at_bats": 'td[data-stat="AB"]',
    "average_leverage_index_pitcher": 'td[data-stat="leverage_index_avg"]',
    "average_leverage_index": 'td[data-stat="leverage_index_avg"]',
    "balks": 'td[data-stat="BK"]',
    "base_out_runs_added": 'td[data-stat="re24_bat"]',
    "base_out_runs_saved": 'td[data-stat="re24_def"]',
    "bases_on_balls_given_per_nine_innings": 'td[data-stat="bases_on_balls_per_nine"]',
    "bases_on_balls_given": 'td[data-stat="BB"]',
    "bases_on_balls": 'td[data-stat="BB"]',
    "batters_faced": 'td[data-stat="batters_faced"]',
    "batters_struckout_per_nine_innings": 'td[data-stat="strikeouts_per_nine"]',
    "batting_average": 'td[data-stat="batting_avg"]',
    "birth_date": 'td[data-stat=""]',
    "complete_games": 'td[data-stat="CG"]',
    "defensive_chances": 'td[data-stat="chances"]',
    "defensive_runs_saved_above_average_per_innings": 'td[data-stat="bis_runs_total_per_season"]',
    "defensive_runs_saved_above_average": 'td[data-stat="bis_runs_total"]',
    "double_plays_turned": 'td[data-stat="DP_def"]',
    "doubles": 'td[data-stat="2B"]',
    "earned_runs_against": 'td[data-stat="earned_run_avg"]',
    "earned_runs_allowed": 'td[data-stat="ER"]',
    "era_plus": 'td[data-stat="earned_run_avg_plus"]',
    "era": 'td[data-stat="earned_run_avg"]',
    "errors": 'td[data-stat="E_def"]',
    "fielding_independent_pitching": 'td[data-stat="fip"]',
    "fielding_percentage": 'td[data-stat="fielding_perc"]',
    "fly_balls": 'td[data-stat="inplay_fb_total"]',
    "game_score": 'td[data-stat="game_score"]',
    "games_catcher": 'td[data-stat="G_c"]',
    "games_center_fielder": 'td[data-stat="G_cf_app"]',
    "games_designated_hitter": 'td[data-stat="G_dh"]',
    "games_finished": 'td[data-stat="GF"]',
    "games_first_baseman": 'td[data-stat="G_1b"]',
    "games_in_batting_order": 'td[data-stat="G_batting"]',
    "games_in_defensive_lineup": 'td[data-stat="G_defense"]',
    "games_left_fielder": 'td[data-stat="G_lf_app"]',
    "games_outfielder": 'td[data-stat="G_of_app"]',
    "games_pinch_hitter": 'td[data-stat="G_ph"]',
    "games_pinch_runner": 'td[data-stat="G_pr"]',
    "games_pitcher": 'td[data-stat="G_p_app"]',
    "games_right_fielder": 'td[data-stat="G_rf_app"]',
    "games_second_baseman": 'td[data-stat="G_2b"]',
    "games_shortstop": 'td[data-stat="G_ss"]',
    "games_started": 'td[data-stat="GS"]',
    "games_third_baseman": 'td[data-stat="G_3b"]',
    "games": 'td[data-stat="G"]',
    "grounded_balls": 'td[data-stat="inplay_gb_total"]',
    "grounded_into_double_plays": 'td[data-stat="GIDP"]',
    "height": 'p span[itemprop="height"]',
    "hits_against_per_nine_innings": 'td[data-stat="hits_per_nine"]',
    "hits_allowed": 'td[data-stat="H"]',
    "hits": 'td[data-stat="H"]',
    "home_runs_against_per_nine_innings": 'td[data-stat="home_runs_per_nine"]',
    "home_runs_allowed": 'td[data-stat="HR"]',
    "home_runs_thrown": 'td[data-stat="HR"]',
    "home_runs": 'td[data-stat="HR"]',
    "inherited_runners": 'td[data-stat="inherited_runners"]',
    "inherited_score": 'td[data-stat="inherited_score"]',
    "innings_pitched": 'td[data-stat="IP"]',
    "innings_played": 'td[data-stat="Inn_def"]',
    "intentional_bases_on_balls_given": 'td[data-stat="IBB"]',
    "intentional_bases_on_balls": 'td[data-stat="IBB"]',
    "league_fielding_percentage": 'td[data-stat="fielding_perc_lg"]',
    "league_range_factor_per_game": 'td[data-stat="range_factor_per_game_lg"]',
    "league_range_factor_per_nine_innings": 'td[data-stat="range_factor_per_nine_lg"]',
    "line_drives": 'td[data-stat="inplay_ld"]',
    "losses": 'td[data-stat="L"]',
    "name": 'h1[itemprop="name"]',
    "nationality": 'td[data-stat=""]',
    "on_base_percentage": 'td[data-stat="onbase_perc"]',
    "on_base_plus_slugging_percentage_plus": 'td[data-stat="onbase_plus_slugging_plus"]',
    "on_base_plus_slugging_percentage": 'td[data-stat="onbase_plus_slugging"]',
    "pitches_thrown": 'td[data-stat="pitches"]',
    "plate_appearances": 'td[data-stat="PA"]',
    "position": 'td[data-stat="pos"]',
    "putouts": 'td[data-stat="PO"]',
    "range_factor_per_game": 'td[data-stat="range_factor_per_game"]',
    "range_factor_per_nine_innings": 'td[data-stat="range_factor_per_nine"]',
    "runs_allowed": 'td[data-stat="R"]',
    "runs_batted_in": 'td[data-stat="RBI"]',
    "runs": 'td[data-stat="R"]',
    "sacrifice_flies": 'td[data-stat="SF"]',
    "sacrifice_hits": 'td[data-stat="SH"]',
    "saves": 'td[data-stat="SV"]',
    "season": 'th[data-stat="year_ID"]',
    "shutouts": 'td[data-stat="SHO"]',
    "slugging_percentage": 'td[data-stat="slugging_perc"]',
    "stolen_bases": 'td[data-stat="SB"]',
    "strikeouts_thrown_per_walk": 'td[data-stat="strikeouts_per_base_on_balls"]',
    "strikeouts": 'td[data-stat="SO"]',
    "strikes_contact": 'td[data-stat="strikes_contact"]',
    "strikes_looking": 'td[data-stat="strikes_looking"]',
    "strikes_swinging": 'td[data-stat="strikes_swinging"]',
    "strikes_thrown": 'td[data-stat="strikes_total"]',
    "strikes": 'td[data-stat="strikes_total"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "team_abbreviation": 'td[data-stat="team_ID"]',
    "times_caught_stealing": 'td[data-stat="CS"]',
    "times_hit_by_pitch": 'td[data-stat="HBP"]',
    "times_hit_player": 'td[data-stat="HBP"]',
    "times_struck_out": 'td[data-stat="SO"]',
    "total_bases": 'td[data-stat="TB"]',
    "total_fielding_runs_above_average_per_innings": 'td[data-stat="tz_runs_total_per_season"]',
    "total_fielding_runs_above_average": 'td[data-stat="tz_runs_total"]',
    "triples": 'td[data-stat="3B"]',
    "unknown_bat_types": 'td[data-stat="inplay_unk"]',
    "weight": 'p span[itemprop="weight"]',
    "whip": 'td[data-stat="whip"]',
    "wild_pitches": 'td[data-stat="WP"]',
    "win_percentage": 'td[data-stat="win_loss_perc"]',
    "win_probability_added_pitcher": 'td[data-stat="wpa_def"]',
    "win_probability_added": 'td[data-stat="wpa_bat_pos"]',
    "win_probability_for_offensive_player": 'td[data-stat="wpa_bat"]',
    "win_probability_subtracted": 'td[data-stat="wpa_bat_neg"]',
    "wins": 'td[data-stat="W"]',
}

PLAYER_ELEMENT_INDEX = {
    "average_leverage_index_pitcher": 1,
    "bases_on_balls_given": 1,
    "hits_allowed": 1,
    "home_runs_allowed": 1,
    "intentional_bases_on_balls_given": 1,
    "pitches_thrown": 1,
    "runs_allowed": 1,
    "strikeouts": 1,
    "strikes_thrown": 1,
    "times_hit_player": 1,
}

NATIONALITY = {
    "af": "Afghanistan",
    "as": "American Samoa",
    "at": "Austria",
    "au": "Australia",
    "aw": "Aruba",
    "be": "Belgium",
    "br": "Brazil",
    "bs": "Bahamas",
    "bz": "Belize",
    "ca": "Canada",
    "ch": "Switzerland",
    "cn": "China",
    "co": "Colombia",
    "cu": "Cuba",
    "cw": "Curacao",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "do": "Dominican Replubic",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "gb": "United Kingdom",
    "gr": "Greece",
    "gu": "Guam",
    "hk": "Hong Kong",
    "hn": "Honduras",
    "id": "Indonesia",
    "ie": "Ireland",
    "it": "Italy",
    "jm": "Jamaica",
    "jp": "Japan",
    "kr": "South Korea",
    "lt": "Lithuania",
    "lv": "Latvia",
    "mx": "Mexico",
    "ni": "Nicaragua",
    "nl": "Netherlands",
    "no": "Norway",
    "pa": "Panama",
    "pe": "Peru",
    "ph": "Philippines",
    "pl": "Poland",
    "pr": "Puerto Rico",
    "pt": "Portugal",
    "ru": "Russian Federation",
    "sa": "Saudi Arabia",
    "se": "Sweden",
    "si": "Singapore",
    "sk": "Slovakia",
    "tw": "Taiwan",
    "us": "United States of America",
    "ve": "Venezuela",
    "vi": "U.S. Virgin Islands",
    "vn": "Viet Nam",
    "za": "South Africa",
}

DOUBLE_HEADER_INDICES = {
    "time": "start time",
    "attendance": "attendance",
    "venue": "venue",
    "duration": "game duration",
}

STANDINGS_URL = "https://www.baseball-reference.com/leagues/MLB/%s-standings.shtml"
TEAM_STATS_URL = "https://www.baseball-reference.com/leagues/MLB/%s.shtml"

SCHEDULE_URL = "https://www.baseball-reference.com/teams/%s/%s-schedule-scores.shtml"

BOXSCORE_URL = "https://www.baseball-reference.com/boxes/%s.shtml"

BOXSCORES_URL = "https://www.baseball-reference.com/boxes/?year=%s&month=%s&day=%s"
PLAYER_URL = "https://www.baseball-reference.com/players/%s/%s.shtml"
ROSTER_URL = "https://www.baseball-reference.com/teams/%s/%s.shtml"

NIGHT = "Night"
DAY = "Day"
