PARSING_SCHEME = {
    "conference_losses": 'td[data-stat="losses_conf"]:first',
    "conference_win_percentage": 'td[data-stat="win_loss_pct_conf"]:first',
    "conference_wins": 'td[data-stat="wins_conf"]:first',
    "conference": 'td[data-stat="conf_abbr"] a',
    "current_rank": 'td[data-stat="rank_current"]:first',
    "first_downs_from_penalties": 'td[data-stat="first_down_penalty"]:first',
    "first_downs": 'td[data-stat="first_down"]:first',
    "fumbles_lost": 'td[data-stat="fumbles_lost"]:first',
    "games": 'td[data-stat="g"]:first',
    "highest_rank": 'td[data-stat="rank_min"]:first',
    "interceptions": 'td[data-stat="pass_int"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "name": "a",
    "opponents_first_downs_from_penalties": 'td[data-stat="opp_first_down_penalty"]:first',
    "opponents_first_downs": 'td[data-stat="opp_first_down"]:first',
    "opponents_fumbles_lost": 'td[data-stat="opp_fumbles_lost"]:first',
    "opponents_interceptions": 'td[data-stat="opp_pass_int"]:first',
    "opponents_pass_attempts": 'td[data-stat="opp_pass_att"]:first',
    "opponents_pass_completion_percentage": 'td[data-stat="opp_pass_cmp_pct"]:first',
    "opponents_pass_completions": 'td[data-stat="opp_pass_cmp"]:first',
    "opponents_pass_first_downs": 'td[data-stat="opp_first_down_pass"]:first',
    "opponents_pass_touchdowns": 'td[data-stat="opp_pass_td"]:first',
    "opponents_pass_yards": 'td[data-stat="opp_pass_yds"]:first',
    "opponents_penalties": 'td[data-stat="opp_penalty"]:first',
    "opponents_plays": 'td[data-stat="opp_tot_plays"]:first',
    "opponents_rush_attempts": 'td[data-stat="opp_rush_att"]:first',
    "opponents_rush_first_downs": 'td[data-stat="opp_first_down_rush"]:first',
    "opponents_rush_touchdowns": 'td[data-stat="opp_rush_td"]:first',
    "opponents_rush_yards_per_attempt": 'td[data-stat="opp_rush_yds_per_att"]:first',
    "opponents_rush_yards": 'td[data-stat="opp_rush_yds"]:first',
    "opponents_turnovers": 'td[data-stat="opp_turnovers"]:first',
    "opponents_yards_from_penalties": 'td[data-stat="opp_penalty_yds"]:first',
    "opponents_yards_per_play": 'td[data-stat="opp_tot_yds_per_play"]:first',
    "opponents_yards": 'td[data-stat="opp_tot_yds"]:first',
    "pass_attempts": 'td[data-stat="pass_att"]:first',
    "pass_completion_percentage": 'td[data-stat="pass_cmp_pct"]:first',
    "pass_completions": 'td[data-stat="pass_cmp"]:first',
    "pass_first_downs": 'td[data-stat="first_down_pass"]:first',
    "pass_touchdowns": 'td[data-stat="pass_td"]:first',
    "pass_yards": 'td[data-stat="pass_yds"]:first',
    "penalties": 'td[data-stat="penalty"]:first',
    "plays": 'td[data-stat="tot_plays"]:first',
    "points_against_per_game": 'td[data-stat="opp_points_per_g"]:first',
    "points_per_game": 'td[data-stat="points_per_g"]:first',
    "preseason_rank": 'td[data-stat="rank_pre"]:first',
    "rush_attempts": 'td[data-stat="rush_att"]:first',
    "rush_first_downs": 'td[data-stat="first_down_rush"]:first',
    "rush_touchdowns": 'td[data-stat="rush_td"]:first',
    "rush_yards_per_attempt": 'td[data-stat="rush_yds_per_att"]:first',
    "rush_yards": 'td[data-stat="rush_yds"]:first',
    "simple_rating_system": 'td[data-stat="srs"]:first',
    "strength_of_schedule": 'td[data-stat="sos"]:first',
    "turnovers": 'td[data-stat="turnovers"]:first',
    "win_percentage": 'td[data-stat="win_loss_pct"]:first',
    "wins": 'td[data-stat="wins"]:first',
    "yards_from_penalties": 'td[data-stat="penalty_yds"]:first',
    "yards_per_play": 'td[data-stat="tot_yds_per_play"]:first',
    "yards": 'td[data-stat="tot_yds"]:first',
}

SCHEDULE_SCHEME = {
    "date": 'td[data-stat="date_game"]:first',
    "day_of_week": 'td[data-stat="day_name"]:first',
    "game": 'th[data-stat="g"]:first',
    "location": 'td[data-stat="game_location"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "opponent_abbr": 'td[data-stat="opp_name"]:first',
    "opponent_conference": 'td[data-stat="conf_abbr"]:first',
    "opponent_name": 'td[data-stat="opp_name"]:first',
    "opponent_rank": 'td[data-stat="opp_name"]:first',
    "points_against": 'td[data-stat="opp_points"]:first',
    "points_for": 'td[data-stat="points"]:first',
    "rank": 'td[data-stat="school_name"]:first',
    "result": 'td[data-stat="game_result"]:first',
    "streak": 'td[data-stat="game_streak"]:first',
    "time": 'td[data-stat="time_game"]:first',
    "wins": 'td[data-stat="wins"]:first',
}

BOXSCORE_SCHEME = {
    "attendance": 'div[class="scorebox_meta"]:first',
    "away_first_downs": 'td[data-stat="vis_stat"]',
    "away_fourth_down_attempts": 'td[data-stat="vis_stat"]',
    "away_fourth_down_conversions": 'td[data-stat="vis_stat"]',
    "away_fumbles_lost": 'td[data-stat="vis_stat"]',
    "away_fumbles": 'td[data-stat="vis_stat"]',
    "away_interceptions": 'td[data-stat="vis_stat"]',
    "away_name": 'a[itemprop="name"]:last',
    "away_net_pass_yards": 'td[data-stat="vis_stat"]',
    "away_pass_attempts": 'td[data-stat="vis_stat"]',
    "away_pass_completions": 'td[data-stat="vis_stat"]',
    "away_pass_touchdowns": 'td[data-stat="vis_stat"]',
    "away_pass_yards": 'td[data-stat="vis_stat"]',
    "away_penalties": 'td[data-stat="vis_stat"]',
    "away_points": 'div[class="scorebox"] div[class="score"]',
    "away_rush_attempts": 'td[data-stat="vis_stat"]',
    "away_rush_touchdowns": 'td[data-stat="vis_stat"]',
    "away_rush_yards": 'td[data-stat="vis_stat"]',
    "away_third_down_attempts": 'td[data-stat="vis_stat"]',
    "away_third_down_conversions": 'td[data-stat="vis_stat"]',
    "away_time_of_possession": 'td[data-stat="vis_stat"]',
    "away_times_sacked": 'td[data-stat="vis_stat"]',
    "away_total_yards": 'td[data-stat="vis_stat"]',
    "away_turnovers": 'td[data-stat="vis_stat"]',
    "away_yards_from_penalties": 'td[data-stat="vis_stat"]',
    "away_yards_lost_from_sacks": 'td[data-stat="vis_stat"]',
    "date": 'div[class="scorebox_meta"]:first',
    "duration": 'div[class="scorebox_meta"]:first',
    "home_first_downs": 'td[data-stat="home_stat"]',
    "home_fourth_down_attempts": 'td[data-stat="home_stat"]',
    "home_fourth_down_conversions": 'td[data-stat="home_stat"]',
    "home_fumbles_lost": 'td[data-stat="home_stat"]',
    "home_fumbles": 'td[data-stat="home_stat"]',
    "home_interceptions": 'td[data-stat="home_stat"]',
    "home_name": 'a[itemprop="name"]:first',
    "home_net_pass_yards": 'td[data-stat="home_stat"]',
    "home_pass_attempts": 'td[data-stat="home_stat"]',
    "home_pass_completions": 'td[data-stat="home_stat"]',
    "home_pass_touchdowns": 'td[data-stat="home_stat"]',
    "home_pass_yards": 'td[data-stat="home_stat"]',
    "home_penalties": 'td[data-stat="home_stat"]',
    "home_points": 'div[class="scorebox"] div[class="score"]',
    "home_rush_attempts": 'td[data-stat="home_stat"]',
    "home_rush_touchdowns": 'td[data-stat="home_stat"]',
    "home_rush_yards": 'td[data-stat="home_stat"]',
    "home_third_down_attempts": 'td[data-stat="home_stat"]',
    "home_third_down_conversions": 'td[data-stat="home_stat"]',
    "home_time_of_possession": 'td[data-stat="home_stat"]',
    "home_times_sacked": 'td[data-stat="home_stat"]',
    "home_total_yards": 'td[data-stat="home_stat"]',
    "home_turnovers": 'td[data-stat="home_stat"]',
    "home_yards_from_penalties": 'td[data-stat="home_stat"]',
    "home_yards_lost_from_sacks": 'td[data-stat="home_stat"]',
    "stadium": 'div[class="scorebox_meta"]:first',
    "time": 'div[class="scorebox_meta"]:first',
}

BOXSCORE_SCHEME = {
    "away_first_downs": 'td[data-stat="vis_stat"]',
    "away_fumbles_lost": 'td[data-stat="vis_stat"]',
    "away_fumbles": 'td[data-stat="vis_stat"]',
    "away_interceptions": 'td[data-stat="vis_stat"]',
    "away_name": 'a[itemprop="name"]:first',
    "away_pass_attempts": 'td[data-stat="vis_stat"]',
    "away_pass_completions": 'td[data-stat="vis_stat"]',
    "away_pass_touchdowns": 'td[data-stat="vis_stat"]',
    "away_pass_yards": 'td[data-stat="vis_stat"]',
    "away_penalties": 'td[data-stat="vis_stat"]',
    "away_points": 'div[class="scorebox"] div[class="score"]',
    "away_rush_attempts": 'td[data-stat="vis_stat"]',
    "away_rush_touchdowns": 'td[data-stat="vis_stat"]',
    "away_rush_yards": 'td[data-stat="vis_stat"]',
    "away_total_yards": 'td[data-stat="vis_stat"]',
    "away_turnovers": 'td[data-stat="vis_stat"]',
    "away_yards_from_penalties": 'td[data-stat="vis_stat"]',
    "date": 'div[class="scorebox_meta"]:first',
    "home_first_downs": 'td[data-stat="home_stat"]',
    "home_fumbles_lost": 'td[data-stat="home_stat"]',
    "home_fumbles": 'td[data-stat="home_stat"]',
    "home_interceptions": 'td[data-stat="home_stat"]',
    "home_name": 'a[itemprop="name"]:last',
    "home_pass_attempts": 'td[data-stat="home_stat"]',
    "home_pass_completions": 'td[data-stat="home_stat"]',
    "home_pass_touchdowns": 'td[data-stat="home_stat"]',
    "home_pass_yards": 'td[data-stat="home_stat"]',
    "home_penalties": 'td[data-stat="home_stat"]',
    "home_points": 'div[class="scorebox"] div[class="score"]',
    "home_rush_attempts": 'td[data-stat="home_stat"]',
    "home_rush_touchdowns": 'td[data-stat="home_stat"]',
    "home_rush_yards": 'td[data-stat="home_stat"]',
    "home_total_yards": 'td[data-stat="home_stat"]',
    "home_turnovers": 'td[data-stat="home_stat"]',
    "home_yards_from_penalties": 'td[data-stat="home_stat"]',
    "stadium": 'div[class="scorebox_meta"]:first',
    "summary": 'table[class="linescore nohover stats_table no_freeze"]:first',
    "time": 'div[class="scorebox_meta"]:first',
}

BOXSCORE_ELEMENT_INDEX = {
    "away_first_downs": 0,
    "away_fumbles_lost": 4,
    "away_fumbles": 4,
    "away_interceptions": 2,
    "away_pass_attempts": 2,
    "away_pass_completions": 2,
    "away_pass_touchdowns": 2,
    "away_pass_yards": 2,
    "away_penalties": 6,
    "away_points": 0,
    "away_rush_attempts": 1,
    "away_rush_touchdowns": 1,
    "away_rush_yards": 1,
    "away_total_yards": 3,
    "away_turnovers": 5,
    "away_yards_from_penalties": 6,
    "date": 0,
    "home_first_downs": 0,
    "home_fumbles_lost": 4,
    "home_fumbles": 4,
    "home_interceptions": 2,
    "home_pass_attempts": 2,
    "home_pass_completions": 2,
    "home_pass_touchdowns": 2,
    "home_pass_yards": 2,
    "home_penalties": 6,
    "home_points": 1,
    "home_rush_attempts": 1,
    "home_rush_touchdowns": 1,
    "home_rush_yards": 1,
    "home_total_yards": 3,
    "home_turnovers": 5,
    "home_yards_from_penalties": 6,
    "stadium": 2,
    "time": 1,
}

# Designates the index of the item within the requested tag
BOXSCORE_ELEMENT_SUB_INDEX = {
    "away_fumbles_lost": 1,
    "away_fumbles": 0,
    "away_interceptions": 4,
    "away_pass_attempts": 1,
    "away_pass_completions": 0,
    "away_pass_touchdowns": 3,
    "away_pass_yards": 2,
    "away_penalties": 0,
    "away_rush_attempts": 0,
    "away_rush_touchdowns": 2,
    "away_rush_yards": 1,
    "away_yards_from_penalties": 1,
    "home_fumbles_lost": 1,
    "home_fumbles": 0,
    "home_interceptions": 4,
    "home_pass_attempts": 1,
    "home_pass_completions": 0,
    "home_pass_touchdowns": 3,
    "home_pass_yards": 2,
    "home_penalties": 0,
    "home_rush_attempts": 0,
    "home_rush_touchdowns": 2,
    "home_rush_yards": 1,
    "home_yards_from_penalties": 1,
}

PLAYER_SCHEME = {
    "adjusted_yards_per_attempt": 'td[data-stat="adj_pass_yds_per_att"]',
    "assists_on_tackles": 'td[data-stat="tackles_assists"]',
    "average_kickoff_return_yards": 'td[data-stat="kick_ret_yds_per_ret"]',
    "average_punt_return_yards": 'td[data-stat="punt_ret_yds"]',
    "completed_passes": 'td[data-stat="pass_cmp"]',
    "extra_point_percentage": 'td[data-stat="xp_pct"]',
    "extra_points_attempted": 'td[data-stat="xpa"]',
    "extra_points_made": 'td[data-stat="xpm"]',
    "field_goal_percentage": 'td[data-stat="fg_pct"]',
    "field_goals_attempted": 'td[data-stat="fga"]',
    "field_goals_made": 'td[data-stat="fgm"]',
    "fumbles_forced": 'td[data-stat="fumbles_forced"]',
    "fumbles_recovered_for_touchdown": 'td[data-stat="fumbles_rec_td"]',
    "fumbles_recovered": 'td[data-stat="fumbles_rec"]',
    "games": 'td[data-stat="g"]',
    "height": 'span[itemprop="height"]',
    "interceptions_returned_for_touchdown": 'td[data-stat="def_int_td"]',
    "interceptions_thrown": 'td[data-stat="pass_int"]',
    "interceptions": 'td[data-stat="def_int"]',
    "kickoff_return_touchdowns": 'td[data-stat="td_kick_ret"]',
    "kickoff_return_yards": 'td[data-stat="kick_ret_yds"]',
    "kickoff_returns": 'td[data-stat="kick_ret"]',
    "name": 'h1[itemprop="name"]',
    "other_touchdowns": 'td[data-stat="td_other"]',
    "pass_attempts": 'td[data-stat="pass_att"]',
    "pass_yards_per_attempt": 'td[data-stat="pass_yds_per_att"]',
    "passes_defended": 'td[data-stat="pass_defended"]',
    "passing_completion": 'td[data-stat="pass_cmp_pct"]',
    "passing_touchdowns": 'td[data-stat="pass_td"]',
    "passing_yards_per_attempt": 'td[data-stat="pass_yds_per_att"]',
    "passing_yards": 'td[data-stat="pass_yds"]',
    "plays_from_scrimmage": 'td[data-stat="scrim_att"]',
    "points_kicking": 'td[data-stat="kick_points"]',
    "points": 'td[data-stat="points"]',
    "position": 'td[data-stat="pos"]',
    "punt_return_touchdowns": 'td[data-stat="td_punt_ret"]',
    "punt_return_yards": 'td[data-stat="punt_ret_yds"]',
    "punt_returns": 'td[data-stat="punt_ret"]',
    "punting_yards_per_attempt": 'td[data-stat="punt_yds_per_punt"]',
    "punting_yards": 'td[data-stat="punt_yds"]',
    "punts": 'td[data-stat="punt"]',
    "quarterback_rating": 'td[data-stat="pass_rating"]',
    "receiving_touchdowns": 'td[data-stat="rec_td"]',
    "receiving_yards_per_reception": 'td[data-stat="rec_yds_per_rec"]',
    "receiving_yards": 'td[data-stat="rec_yds"]',
    "receptions": 'td[data-stat="rec"]',
    "rush_attempts": 'td[data-stat="rush_att"]',
    "rush_touchdowns": 'td[data-stat="rush_td"]',
    "rush_yards_per_attempt": 'td[data-stat="rush_yds_per_att"]',
    "rush_yards": 'td[data-stat="rush_yds"]',
    "rushing_and_receiving_touchdowns": 'td[data-stat="scrim_td"]',
    "sacks": 'td[data-stat="sacks"]',
    "safeties": 'td[data-stat="safety_md"]',
    "season": 'th[data-stat="year_id"]',
    "solo_tackles": 'td[data-stat="tackles_solo"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "tackles_for_loss": 'td[data-stat="tackles_loss"]',
    "team_abbreviation": 'td[data-stat="school_name"]',
    "total_tackles": 'td[data-stat="tackles_total"]',
    "total_touchdowns": 'td[data-stat="td_total"]',
    "two_point_conversions": 'td[data-stat="two_pt_md"]',
    "weight": 'span[itemprop="weight"]',
    "yards_from_scrimmage_per_play": 'td[data-stat="scrim_yds_per_att"]',
    "yards_from_scrimmage": 'td[data-stat="scrim_yds"]',
    "yards_recovered_from_fumble": 'td[data-stat="fumbles_rec_yds"]',
    "yards_returned_from_interceptions": 'td[data-stat="def_int_yds"]',
    "yards_returned_per_interception": 'td[data-stat="def_int_yds_per_int"]',
    "year": 'td[data-stat="class"]',
}

BOXSCORE_RETRY = {
    "kickoff_return_touchdowns": 'td[data-stat="kick_ret_td"]',
    "punt_return_touchdowns": 'td[data-stat="punt_ret_td"]',
}

RANKINGS_SCHEME = {
    "change": 'td[data-stat="rank_diff"]',
    "date": 'td[data-stat="date_poll"]',
    "name": 'td[data-stat="school_name"]',
    "previous": 'td[data-stat="rank_prev"]',
    "rank": 'td[data-stat="rank"]',
    "week": 'th[data-stat="week_poll"]',
}

SEASON_PAGE_URL = "http://www.sports-reference.com/cfb/years/%s-standings.html"

OFFENSIVE_STATS_URL = "https://www.sports-reference.com/cfb/years/%s-team-offense.html"
DEFENSIVE_STATS_URL = "https://www.sports-reference.com/cfb/years/%s-team-defense.html"

SCHEDULE_URL = "https://www.sports-reference.com/cfb/schools/%s/%s-schedule.html"

BOXSCORE_URL = "https://www.sports-reference.com/cfb/boxscores/%s.html"

BOXSCORES_URL = (
    "https://www.sports-reference.com/cfb/boxscores/index.cgi?month=%s&day=%s&year=%s&conf_id="
)
CONFERENCES_URL = "https://www.sports-reference.com/cfb/years/%s.html"
CONFERENCE_URL = "https://www.sports-reference.com/cfb/conferences/%s/%s.html"
CFP_RANKINGS_URL = "https://www.sports-reference.com/cfb/years/%s-polls.html"
COACHES_RANKINGS_URL = "https://www.sports-reference.com/cfb/years/%s-polls.html"
RANKINGS_URL = "https://www.sports-reference.com/cfb/years/%s-polls.html"
PLAYER_URL = "https://www.sports-reference.com/cfb/players/%s.html"
ROSTER_URL = "https://www.sports-reference.com/cfb/schools/%s/%s-roster.html"
