PARSING_SCHEME = {
    "average_age": 'td[data-stat="average_age"]:first',
    "games_played": 'td[data-stat="games"]:first',
    "goals_against": 'td[data-stat="opp_goals"]:first',
    "goals_for": 'td[data-stat="goals"]:first',
    "losses": 'td[data-stat="losses"]:first',
    "name": "a",
    "overtime_losses": 'td[data-stat="losses_ot"]:first',
    "pdo_at_even_strength": 'td[data-stat="pdo"]:first',
    "penalty_killing_percentage": 'td[data-stat="pen_kill_pct"]:first',
    "points_percentage": 'td[data-stat="points_pct"]:first',
    "points": 'td[data-stat="points"]:first',
    "power_play_goals_against": 'td[data-stat="opp_goals_pp"]:first',
    "power_play_goals": 'td[data-stat="goals_pp"]:first',
    "power_play_opportunities_against": 'td[data-stat="opp_chances_pp"]:first',
    "power_play_opportunities": 'td[data-stat="chances_pp"]:first',
    "power_play_percentage": 'td[data-stat="power_play_pct"]:first',
    "save_percentage": 'td[data-stat="save_pct"]:first',
    "shooting_percentage": 'td[data-stat="shot_pct"]:first',
    "short_handed_goals_against": 'td[data-stat="opp_goals_sh"]:first',
    "short_handed_goals": 'td[data-stat="goals_sh"]:first',
    "shots_against": 'td[data-stat="shots_against"]:first',
    "shots_on_goal": 'td[data-stat="shots"]:first',
    "simple_rating_system": 'td[data-stat="srs"]:first',
    "strength_of_schedule": 'td[data-stat="sos"]:first',
    "total_goals_per_game": 'td[data-stat="total_goals_per_game"]:first',
    "wins": 'td[data-stat="wins"]:first',
}

SCHEDULE_SCHEME = {
    "corsi_against": 'td[data-stat="corsi_against"]:first',
    "corsi_for_percentage": 'td[data-stat="corsi_pct"]:first',
    "corsi_for": 'td[data-stat="corsi_for"]:first',
    "date": 'td[data-stat="date_game"]:first',
    "faceoff_losses": 'td[data-stat="faceoff_losses"]:first',
    "faceoff_win_percentage": 'td[data-stat="faceoff_percentage"]:first',
    "faceoff_wins": 'td[data-stat="faceoff_wins"]:first',
    "fenwick_against": 'td[data-stat="fenwick_against"]:first',
    "fenwick_for_percentage": 'td[data-stat="fenwick_pct"]:first',
    "fenwick_for": 'td[data-stat="fenwick_for"]:first',
    "game": 'th[data-stat="games"]:first',
    "goals_allowed": 'td[data-stat="opp_goals"]:first',
    "goals_scored": 'td[data-stat="goals"]:first',
    "location": 'td[data-stat="game_location"]:first',
    "offensive_zone_start_percentage": 'td[data-stat="zs_offense_pct"]:first',
    "opp_penalties_in_minutes": 'td[data-stat="pen_min_opp"]:first',
    "opp_power_play_goals": 'td[data-stat="goals_against_pp"]:first',
    "opp_power_play_opportunities": 'td[data-stat="opp_chances_pp"]:first',
    "opp_short_handed_goals": 'td[data-stat="goals_against_sh"]:first',
    "opp_shots_on_goal": 'td[data-stat="shots_against"]:first',
    "opponent_abbr": 'td[data-stat="opp_name"]:first',
    "opponent_name": 'td[data-stat="opp_name"]:first',
    "overtime": 'td[data-stat="overtimes"]:first',
    "pdo": 'td[data-stat="pdo"]:first',
    "penalties_in_minutes": 'td[data-stat="pen_min"]:first',
    "power_play_goals": 'td[data-stat="goals_pp"]:first',
    "power_play_opportunities": 'td[data-stat="chances_pp"]:first',
    "result": 'td[data-stat="game_outcome"]:first',
    "short_handed_goals": 'td[data-stat="goals_sh"]:first',
    "shots_on_goal": 'td[data-stat="shots"]:first',
    "time": 'td[data-stat="time_game"]:first',
}

BOXSCORE_SCHEME = {
    "away_assists": 'tfoot td[data-stat="assists"]',
    "away_even_strength_assists": 'td[data-stat="assists_ev"]',
    "away_even_strength_goals": 'tfoot td[data-stat="goals_ev"]',
    "away_game_winning_goals": 'td[data-stat="goals_gw"]',
    "away_goalies": 'table[class="sortable stats_table"]',
    "away_goals": 'tfoot td[data-stat="goals"]',
    "away_name": 'a[itemprop="name"]:first',
    "away_penalties_in_minutes": 'tfoot td[data-stat="pen_min"]',
    "away_points": 'tfoot td[data-stat="points"]',
    "away_power_play_assists": 'td[data-stat="assists_pp"]',
    "away_power_play_goals": 'tfoot td[data-stat="goals_pp"]',
    "away_save_percentage": 'td[data-stat="save_pct"]',
    "away_saves": 'td[data-stat="saves"]',
    "away_shooting_percentage": 'tfoot td[data-stat="shot_pct"]',
    "away_short_handed_assists": 'td[data-stat="assists_sh"]',
    "away_short_handed_goals": 'tfoot td[data-stat="goals_sh"]',
    "away_shots_on_goal": 'tfoot td[data-stat="shots"]',
    "away_shutout": 'td[data-stat="shutouts"]',
    "away_skaters": 'table[class="sortable stats_table"]:first tbody tr',
    "game_info": 'div[class="scorebox_meta"]',
    "home_assists": 'tfoot td[data-stat="assists"]',
    "home_even_strength_assists": 'td[data-stat="assists_ev"]',
    "home_even_strength_goals": 'tfoot td[data-stat="goals_ev"]',
    "home_game_winning_goals": 'td[data-stat="goals_gw"]',
    "home_goals": 'tfoot td[data-stat="goals"]',
    "home_name": 'a[itemprop="name"]:last',
    "home_penalties_in_minutes": 'tfoot td[data-stat="pen_min"]',
    "home_points": 'tfoot td[data-stat="points"]',
    "home_power_play_assists": 'td[data-stat="assists_pp"]',
    "home_power_play_goals": 'tfoot td[data-stat="goals_pp"]',
    "home_save_percentage": 'td[data-stat="save_pct"]',
    "home_saves": 'td[data-stat="saves"]',
    "home_shooting_percentage": 'tfoot td[data-stat="shot_pct"]',
    "home_short_handed_assists": 'td[data-stat="assists_sh"]',
    "home_short_handed_goals": 'tfoot td[data-stat="goals_sh"]',
    "home_shots_on_goal": 'tfoot td[data-stat="shots"]',
    "home_shutout": 'td[data-stat="shutouts"]',
}

BOXSCORE_ELEMENT_INDEX = {
    "arena": 2,
    "attendance": 1,
    "date": 0,
    "duration": 3,
    "home_assists": 1,
    "home_even_strength_goals": 1,
    "home_goals": 1,
    "home_penalties_in_minutes": 1,
    "home_points": 1,
    "home_power_play_goals": 1,
    "home_save_percentage": 1,
    "home_saves": 1,
    "home_shooting_percentage": 1,
    "home_short_handed_goals": 1,
    "home_shots_on_goal": 1,
    "home_shutout": 1,
    "time": 0,
}

PLAYER_SCHEME = {
    "adjusted_assists": 'td[data-stat="assists_adjusted"]',
    "adjusted_goals_against_average": 'td[data-stat="goals_against_avg_adjusted"]',
    "adjusted_goals_created": 'td[data-stat="goals_created_adjusted"]',
    "adjusted_goals": 'td[data-stat="goals_adjusted"]',
    "adjusted_points": 'td[data-stat="points_adjusted"]',
    "age": 'td[data-stat="age"]',
    "assists": 'td[data-stat="assists"]',
    "average_time_on_ice": 'td[data-stat="time_on_ice_avg"]',
    "blocks_at_even_strength": 'td[data-stat="blocks"]',
    "corsi_against": 'td[data-stat="corsi_against"]',
    "corsi_for_percentage": 'td[data-stat="corsi_pct"]',
    "corsi_for": 'td[data-stat="corsi_for"]',
    "decision": 'td[data-stat="decision"]',
    "defensive_point_shares": 'td[data-stat="dps"]',
    "defensive_zone_start_percentage": 'td[data-stat="zs_defense_pct"]',
    "defensive_zone_starts": 'td[data-stat="zs_def"]',
    "even_strength_assists": 'td[data-stat="assists_ev"]',
    "even_strength_goals_allowed": 'td[data-stat="goals_against_ev"]',
    "even_strength_goals": 'td[data-stat="goals_ev"]',
    "even_strength_save_percentage": 'td[data-stat="svpct_ev"]',
    "even_strength_shots_faced": 'td[data-stat="shots_against_ev"]',
    "faceoff_losses": 'td[data-stat="faceoff_losses"]',
    "faceoff_percentage": 'td[data-stat="faceoff_percentage"]',
    "faceoff_wins": 'td[data-stat="faceoff_wins"]',
    "fenwick_against": 'td[data-stat="fenwick_against"]',
    "fenwick_for_percentage": 'td[data-stat="fenwick_pct"]',
    "fenwick_for": 'td[data-stat="fenwick_for"]',
    "game_winning_goals": 'td[data-stat="goals_gw"]',
    "games_played": 'td[data-stat="games_played"]',
    "giveaways": 'td[data-stat="giveaways"]',
    "goal_against_percentage_relative": 'td[data-stat="ga_pct_minus"]',
    "goalie_point_shares": 'td[data-stat="gps"]',
    "goals_against_average": 'td[data-stat="goals_against_avg"]',
    "goals_against_on_ice": 'td[data-stat="on_goals_against"]',
    "goals_against": 'td[data-stat="goals_against"]',
    "goals_created": 'td[data-stat="goals_created"]',
    "goals_for_on_ice": 'td[data-stat="on_goals"]',
    "goals_saved_above_average": 'td[data-stat="gs_above_avg"]',
    "goals": 'td[data-stat="goals"]',
    "height": 'span[itemprop="height"]',
    "hits_at_even_strength": 'td[data-stat="hits"]',
    "individual_corsi_for_events": 'td[data-stat="Cevents"]',
    "league": 'td[data-stat="lg_id"]',
    "losses": 'td[data-stat="losses_goalie"]',
    "minutes": 'td[data-stat="min_goalie"]',
    "name": 'h1[itemprop="name"]',
    "offensive_point_shares": 'td[data-stat="ops"]',
    "offensive_zone_start_percentage": 'td[data-stat="zs_offense_pct"]',
    "offensive_zone_starts": 'td[data-stat="zs_off"]',
    "on_ice_shot_attempts_against": 'td[data-stat="on_opp_Cevents"]',
    "on_ice_shot_attempts_for": 'td[data-stat="on_Cevents"]',
    "pdo": 'td[data-stat="pdo"]',
    "penalties_in_minutes": 'td[data-stat="pen_min"]',
    "plus_minus": 'td[data-stat="plus_minus"]',
    "point_shares": 'td[data-stat="ps"]',
    "points": 'td[data-stat="points"]',
    "power_play_assists": 'td[data-stat="assists_pp"]',
    "power_play_goals_against_on_ice": 'td[data-stat="power_play_goals_against"]',
    "power_play_goals_allowed": 'td[data-stat="goals_against_pp"]',
    "power_play_goals_for_on_ice": 'td[data-stat="power_play_goals_for"]',
    "power_play_goals": 'td[data-stat="goals_pp"]',
    "power_play_save_percentage": 'td[data-stat="svpct_pp"]',
    "power_play_shots_faced": 'td[data-stat="shots_against_pp"]',
    "quality_start_percentage": 'td[data-stat="quality_start_goalie_pct"]',
    "quality_starts": 'td[data-stat="quality_starts_goalie"]',
    "really_bad_starts": 'td[data-stat="really_bad_starts_goalie"]',
    "relative_corsi_for_percentage": 'td[data-stat="corsi_rel_pct"]',
    "relative_fenwick_for_percentage": 'td[data-stat="fenwick_rel_pct"]',
    "save_percentage_on_ice": 'td[data-stat="on_ice_sv_pct"]',
    "save_percentage": 'td[data-stat="save_pct"]',
    "saves": 'td[data-stat="saves"]',
    "season": 'th[data-stat="season"]',
    "shifts": 'td[data-stat="shifts"]',
    "shooting_percentage_on_ice": 'td[data-stat="on_ice_shot_pct"]',
    "shooting_percentage": 'td[data-stat="shot_pct"]',
    "shootout_attempts": 'td[data-stat="so_att"]',
    "shootout_goals": 'td[data-stat="so_made"]',
    "shootout_misses": 'td[data-stat="so_miss"]',
    "shootout_percentage": 'td[data-stat="so_made_pct"]',
    "short_handed_assists": 'td[data-stat="assists_sh"]',
    "short_handed_goals_allowed": 'td[data-stat="goals_against_sh"]',
    "short_handed_goals": 'td[data-stat="goals_sh"]',
    "short_handed_save_percentage": 'td[data-stat="svpct_sh"]',
    "short_handed_shots_faced": 'td[data-stat="shots_against_sh"]',
    "shots_against": 'td[data-stat="shots_against"]',
    "shots_on_goal": 'td[data-stat="shots"]',
    "shutouts": 'td[data-stat="shutouts"]',
    "summary": '[data-template="Partials/Teams/Summary"]',
    "takeaways": 'td[data-stat="takeaways"]',
    "team_abbreviation": 'td[data-stat="team_id"]',
    "ties_plus_overtime_loss": 'td[data-stat="ties_goalie"]',
    "time_on_ice_even_strength": 'td[data-stat="toi_pbp"]',
    "time_on_ice": 'td[data-stat="time_on_ice"]',
    "total_goals_against_on_ice": 'td[data-stat="total_goals_against"]',
    "total_goals_for_on_ice": 'td[data-stat="total_goals_for"]',
    "total_shots": 'td[data-stat="shots_attempted"]',
    "weight": 'span[itemprop="weight"]',
    "wins": 'td[data-stat="wins_goalie"]',
}

BOXSCORE_RETRY = {
    "corsi_for_percentage": 'td[data-stat="corsi_for"]',
    "offensive_zone_start_percentage": 'td[data-stat="ozs_pct"]',
    "relative_corsi_for_percentage": 'td[data-stat="corsi_rel"]',
}

SEASON_PAGE_URL = "http://www.hockey-reference.com/leagues/NHL_%s.html"

SCHEDULE_URL = "https://www.hockey-reference.com/teams/%s/%s_gamelog.html"

BOXSCORE_URL = "https://www.hockey-reference.com/boxscores/%s.html"

BOXSCORES_URL = "https://www.hockey-reference.com/boxscores/index.fcgi?month=%s&day=%s&year=%s"
PLAYER_URL = "https://www.hockey-reference.com/players/%s/%s.html"
ROSTER_URL = "https://www.hockey-reference.com/teams/%s/%s.html"

SHOOTOUT = -1
OVERTIME_LOSS = "OTL"
